
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[202] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,   56,    2,   55,
       51,   56,   54,   54,   51,   51,   51,   51,   27,    4,
       52,   52,   52,   50,   56,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   14,   57,    7,
        8,    9,   14,   10,   13,   13,   13,   23,   22,   23,
       40,   30,   57,   29,   38,   34,   39,   37,   57,   49,
       57,   57,   41,   46,   48,   47,   45,   31,   33,   32,
        2,   55,   53,    0,    0,    0,    0,   20,   19,   27,
       52,    0,   18,   18,   18,   18,   15,   18,   18,   18,

       18,   18,   18,   18,   18,   14,   11,   13,   14,   13,
       13,   21,    0,    0,    0,    0,   37,    0,   47,    0,
       42,    0,    0,    0,    0,   47,   45,   31,   28,    0,
       28,    0,    0,    0,   19,    0,   18,   18,   18,   18,
       18,   18,   18,   18,   11,   11,   14,   13,    5,   36,
        0,   36,    0,    0,    0,   44,    0,   44,    0,    0,
        0,    0,    0,    0,    0,    0,   18,   18,   18,   17,
       18,   12,   13,    0,    0,    0,    0,    0,    0,    0,
        0,   24,    0,   25,    0,    1,   16,   18,   13,    0,
       35,    0,   43,    0,   26,    0,   18,   13,    3,    6,

        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        8,    9,   10,   11,   12,    1,   13,   14,   15,   16,
       17,   17,   17,   17,   17,   18,   17,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   26,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   27,   25,   25,   25,   25,
       28,   29,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   41,   42,   43,   44,
       45,   46,   41,   47,   48,   49,   41,   41,   50,   41,
       41,   41,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    3,    4,    1,    5,    2,    2,    1,    1,
        2,    1,    1,    6,    6,    6,    6,    6,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1
    } ;

static const flex_int16_t yy_base[221] =
    {   0,
        0,    0,   52,    0,    0,    0,  102,  103,  110,    0,
        0,    0,  160,    0,  104,  106,  589,  590,  117,  120,
      566,  558,  122,  590,  564,  563,  562,  119,  199,  561,
      103,  590,  560,  590,  549,    0,  544,  540,  182,   85,
      533,  182,  545,  529,  541,  529,  534,    0,  590,  590,
      590,  590,  559,  590,  227,  279,  190,  590,  590,  558,
      590,  590,  541,  227,  590,  590,  590,    0,  113,  590,
      565,  539,  245,  590,  590,  565,    0,    0,  590,  590,
      132,  218,  590,  224,  261,  256,  302,  590,    0,  279,
      590,  519,    0,  527,  532,  529,    0,  514,  526,  513,

      189,  519,  236,  526,  517,    0,  321,  524,  319,  222,
      233,  590,  246,  309,  337,  345,    0,  285,  553,  550,
      590,  293,  321,  355,  363,  551,    0,    0,  590,  315,
      319,  337,  275,  373,    0,  523,  491,  478,  478,  469,
      465,  459,  445,  446,  385,    0,  368,  332,  451,  590,
      320,  339,  391,  365,  388,  590,  389,  393,  404,  398,
      399,  409,  468,  400,  411,  443,  410,  403,  404,    0,
      395,    0,  274,  414,  412,  426,  421,  407,  433,  436,
      438,  590,  440,  590,  378,    0,    0,  314,  411,  445,
      590,  447,  590,  448,  590,  300,  271,  193,  590,  250,

      590,  456,  462,  468,  474,  260,  480,  486,  492,  218,
      498,  504,  125,  510,  516,  522,  528,  534,  540,  546
    } ;

static const flex_int16_t yy_def[221] =
    {   0,
      201,    1,  201,    3,  202,  202,  203,  203,  202,    9,
      202,  202,  201,   13,  204,  204,  201,  201,  201,  201,
      201,  205,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  207,  201,  201,
      201,  201,  207,  201,  208,  208,   56,  201,  201,  201,
      201,  201,  209,  201,  201,  201,  201,  210,  201,  201,
      211,  212,  201,  201,  201,  201,  213,  214,  201,  201,
      201,  201,  201,  205,  215,  201,  201,  201,  216,  201,
      201,  201,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  207,  217,   56,  207,   56,
       56,  201,  209,  218,  201,  201,  210,  201,  201,  211,
      201,  212,  219,  201,  201,  201,  213,  214,  201,  205,
      205,  215,  201,  201,  216,  201,  206,  206,  206,  206,
      206,  206,  206,  206,  217,  220,  207,   56,   56,  201,
      209,  209,  218,  201,  201,  201,  212,  212,  219,  201,
      201,  201,  201,  201,  201,  201,  206,  206,  206,  206,
      206,  207,   56,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  206,  206,  206,   56,  201,
      201,  201,  201,  201,  201,  201,  206,   56,  201,   56,

        0,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201
    } ;

static const flex_int16_t yy_nxt[643] =
    {   0,
       18,   19,   20,   18,   21,   22,   23,   24,   25,   26,
       24,   27,   28,   29,   29,   29,   29,   29,   30,   24,
       31,   32,   33,   34,   18,   18,   35,   18,   18,   18,
       18,   36,   37,   38,   39,   40,   41,   36,   36,   42,
       36,   36,   43,   36,   36,   44,   36,   45,   46,   47,
       24,   24,   48,   49,   49,   48,   48,   48,   50,   51,
       48,   48,   52,   48,   53,   48,   48,   48,   48,   48,
       48,   54,   48,   48,   48,   48,   55,   55,   56,   48,
       48,   48,   48,   55,   55,   55,   55,   57,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   48,   48,   59,   59,   79,   80,   79,   80,
       60,   60,   61,   62,  118,   63,   64,   65,   81,   82,
       66,   82,   82,   86,   91,   91,   98,   88,   99,   67,
      127,   89,  119,   81,   82,   87,   87,   87,   87,   87,
       83,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       49,   69,   70,   71,   49,   72,   73,   74,   49,   49,
       75,   49,   49,   49,   49,   49,   49,   49,   49,   76,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       49,   49,   90,   90,   90,   90,   90,   96,   97,   82,
       82,  108,   97,  117,  108,  101,   97,  106,  115,  129,
      106,  106,  106,  111,  200,  106,  106,   97,  106,  106,
      116,  116,  116,  116,  116,  106,  124,  106,  106,  106,
      106,  150,   85,  108,  109,  106,  106,   86,  125,  125,
      125,  125,  125,   84,  108,   93,  131,  149,  148,   87,
       87,   87,   87,   87,  114,  141,  133,  106,  106,  106,
      142,  108,  106,  106,  106,  134,  118,  106,  106,  132,
      106,  106,   90,   90,   90,   90,   90,  106,  156,  106,

      106,  106,  106,  133,  119,  108,  109,  106,  106,  189,
      110,  113,  134,   97,  152,   87,   87,   87,   87,   87,
      129,  123,  146,  122,  129,  150,  158,  146,  146,  106,
      106,  146,  147,  147,  147,  147,  147,  153,  115,   84,
      146,  199,  131,   85,  150,  197,  154,   85,  114,  159,
      116,  116,  116,  116,  116,  155,  124,  173,  116,  116,
      116,  116,  116,  108,  160,  132,  154,  114,  125,  125,
      125,  125,  125,  161,  162,  155,  125,  125,  125,  125,
      125,  147,  147,  147,  147,  147,  146,  163,  164,  174,
      165,  146,  146,  113,  156,  146,  152,  172,  156,  160,

      177,  181,  175,  176,  146,  176,  122,  182,  161,  158,
      162,  196,  183,  178,  179,  174,  179,  123,  184,  153,
      179,  123,  177,  163,  164,  176,  165,  190,  175,  176,
       97,  176,  159,  191,  192,  178,  179,  194,  179,  181,
      193,  183,  108,  195,  198,  182,  190,  184,  192,  194,
      188,  187,  191,  186,  193,  195,   49,   49,   49,   49,
       49,   49,   58,   58,   58,   58,   58,   58,   78,   78,
       78,   78,   78,   78,   84,   84,   84,   84,  185,   84,
      106,  180,  108,  106,  106,  106,  108,  171,  170,  108,
      108,  108,  113,  113,  113,  113,  169,  113,  120,  120,

      120,  120,  120,  120,  122,  122,  122,  122,  168,  122,
      128,  128,   97,   97,  128,  128,  130,  130,  130,  130,
      130,  130,  135,  135,   97,  135,  135,  135,  145,  145,
      167,  145,  145,  145,  151,  151,  151,  151,  151,  151,
      157,  157,  157,  157,  157,  157,  146,  146,  166,  146,
      146,  146,  126,  121,  126,  108,  144,  143,  140,   97,
       97,  139,   97,  138,  137,  136,  126,  123,  121,  114,
      112,  107,  105,   97,  104,  103,  102,  100,   95,   94,
       92,   91,   83,   83,   83,   83,   85,   83,  201,   17,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201
    } ;

static const flex_int16_t yy_chk[643] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    7,    8,   15,   15,   16,   16,
        7,    8,    9,    9,   69,    9,    9,    9,   19,   19,
        9,   20,   20,   23,   31,   31,   40,   28,   40,    9,
      213,   28,   69,   81,   81,   23,   23,   23,   23,   23,
       28,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   29,   29,   29,   29,   29,   39,   42,   82,
       82,   57,  101,  210,  198,   42,   39,   55,   64,   84,
       55,   55,   55,   57,  198,   55,   55,  101,   55,   55,
       64,   64,   64,   64,   64,   55,   73,   55,   55,   55,
       55,  113,   84,  110,   55,   55,   55,   86,   73,   73,
       73,   73,   73,   85,  111,  206,   85,  111,  110,   86,
       86,   86,   86,   86,  113,  103,  133,   55,   55,   56,
      103,  200,   56,   56,   56,  133,  118,   56,   56,   85,
       56,   56,   90,   90,   90,   90,   90,   56,  122,   56,

       56,   56,   56,   87,  118,  173,   56,   56,   56,  173,
       56,  114,   87,  197,  114,   87,   87,   87,   87,   87,
      130,  122,  107,  123,  131,  151,  123,  107,  107,   56,
       56,  107,  109,  109,  109,  109,  109,  114,  115,  132,
      107,  196,  132,  130,  152,  188,  116,  131,  151,  123,
      115,  115,  115,  115,  115,  116,  124,  148,  116,  116,
      116,  116,  116,  148,  125,  132,  154,  152,  124,  124,
      124,  124,  124,  125,  134,  154,  125,  125,  125,  125,
      125,  147,  147,  147,  147,  147,  145,  134,  134,  155,
      134,  145,  145,  153,  157,  145,  153,  147,  158,  160,

      161,  164,  155,  155,  145,  155,  159,  164,  160,  159,
      162,  185,  165,  161,  161,  174,  161,  157,  165,  153,
      178,  158,  177,  162,  162,  175,  162,  176,  174,  174,
      171,  174,  159,  176,  179,  177,  177,  180,  177,  181,
      179,  183,  189,  180,  189,  181,  190,  183,  192,  194,
      169,  168,  190,  167,  192,  194,  202,  202,  202,  202,
      202,  202,  203,  203,  203,  203,  203,  203,  204,  204,
      204,  204,  204,  204,  205,  205,  205,  205,  166,  205,
      207,  163,  149,  207,  207,  207,  208,  144,  143,  208,
      208,  208,  209,  209,  209,  209,  142,  209,  211,  211,

      211,  211,  211,  211,  212,  212,  212,  212,  141,  212,
      214,  214,  140,  139,  214,  214,  215,  215,  215,  215,
      215,  215,  216,  216,  138,  216,  216,  216,  217,  217,
      137,  217,  217,  217,  218,  218,  218,  218,  218,  218,
      219,  219,  219,  219,  219,  219,  220,  220,  136,  220,
      220,  220,  126,  120,  119,  108,  105,  104,  102,  100,
       99,   98,   96,   95,   94,   92,   76,   72,   71,   63,
       60,   53,   47,   46,   45,   44,   43,   41,   38,   37,
       35,   33,   30,   27,   26,   25,   22,   21,   17,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexerpart1.l"
#line 2 "lexerpart1.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_COMMENT_SIZE 2048
static char comment_buffer[MAX_COMMENT_SIZE];
static int comment_index = 0;
static char scan_args[1024];
static char print_string[1024];
static char print_args[1024];
static int print_state_string_captured = 0;
static int at_count = 0;
static int arg_count = 0;
static int parentheses_count = 0;
static int varDeclPos = 0;
static char* symbolTable[256];
static int symbolCount = 0;
static int varDeclFlag = 0;

int isDeclared(const char* id) {
    int i;
    for(i = 0; i < symbolCount; i++){
        if(strcmp(symbolTable[i], id) == 0) return 1;
    }
    return 0;
}

void reset_print_buffers() {
    memset(print_string, 0, sizeof(print_string));
    memset(print_args, 0, sizeof(print_args));
    print_state_string_captured = 0;
    at_count = 0;
    arg_count = 0;
    parentheses_count = 0;
}

void count_at_symbols(const char* s) {
    int i;
    for (i = 0; s[i]; i++) {
        if (s[i] == '@') at_count++;
    }
}

void finalize_print_statement() {
    char temp[1204];
    if(strlen(print_args) > 0)
         snprintf(temp, sizeof(temp), "print(\"%s\", %s);", print_string, print_args);
    else
         snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    
    if (!print_state_string_captured) {
         printf("\t%-20s\t\t%s\t\n", temp, "Error: Invalid output statement");
         return;
    }
    if (at_count != arg_count) {
         char err_msg[256];
         snprintf(err_msg, sizeof(err_msg), "Error: Invalid output statement");
         printf("\t%-20s\t\t%s\t\n", temp, err_msg);
         return;
    }
    
    printf("\t%-20s\t\t%s\t\n", temp, "Valid output statement");
}

int validate_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (text[0] < 'a' || text[0] > 'z') return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9')) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_char_const(const char *text) {
    int len = strlen(text);
    if (text[0] == '\'' && text[len - 1] == '\'') {
        if (text[1] == '\\' && len == 4) return 1;
        else if (text[1] != '\\' && len == 3) return 1;
    }
    return 0;
}

int validate_decimal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '9') return 0;
    }
    return 1;
}

int validate_octal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '7') return 0;
    }
    return 1;
}

int validate_binary(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] != '0' && text[i] != '1') return 0;
    }
    return 1;
}

int scan_arg_count=0;
int scan_paranthesis_count=0;
int scan_symbol_count=0;
int scan_fl=0;
char scan_string[1024];

void reset_scan_buffers(){
    scan_arg_count = 0;
    scan_paranthesis_count = 0;
    scan_symbol_count = 0;
    scan_fl = 0;
    scan_string[0] = '\0';
    scan_args[0] = '\0';
}

void count_all_symbols(char*str)
{
    int idx=0;
    while(str[idx]!='\0')
    {
        if(str[idx]=='@')
        {
            scan_symbol_count++;
        }
        idx++;
    }
}

int validate_scan_placeholders(const char *s) {
    int atCount = 0, commaCount = 0;
    int len = strlen(s);
    int start = 0, end = len;

    if (len >= 2 && s[0] == '\"' && s[len - 1] == '\"') {
        start = 1;
        end = len - 1;
    }
    for (int i = start; i < end; i++) {
         if (s[i] == '\"')
             return 0;
         if (s[i] == '@')
             atCount++;
         else if (s[i] == ',')
             commaCount++;
    }
    if (atCount < 1 || commaCount != atCount - 1)
         return 0;
    return 1;
}
int statement_fl=0;
int isKeyword(const char *word) {
    const char *keywords[] = {
        "begin", "end", "VarDecl", "int", "char", "if", "else", "while",
        "for", "print", "scan", "program", "inc", "dec", "do", "to", "main", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(word, keywords[i]) == 0)
            return 1;
    }
    return 0;
}

#line 841 "lex.yy.c"

#line 843 "lex.yy.c"

#define INITIAL 0
#define VARDECL 1
#define NUMRELATIONS 2
#define COMMENT 3
#define PRINT 4
#define CONDITION 5
#define SCAN 6
#define STRING 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 200 "lexerpart1.l"


#line 1070 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 202 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 590 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 202 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 206 "lexerpart1.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 208 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
    varDeclFlag = 1;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 213 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
    if (varDeclFlag) {
         BEGIN(VARDECL);
         varDeclFlag = 0;
    }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 221 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 225 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
    BEGIN(INITIAL);
}
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 231 "lexerpart1.l"
{ 
         varDeclPos = 0;
         printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 235 "lexerpart1.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
         varDeclPos = 0;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 239 "lexerpart1.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 242 "lexerpart1.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 245 "lexerpart1.l"
{ 
         //printf("\t%-20s\t\t%s\t\n", yytext, "Comment");
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 248 "lexerpart1.l"
{
         char arrName[256], sizeStr[64];
         if (sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr) == 2) {
             if (varDeclPos == 0) {
                 if (isKeyword(arrName)) {
                     printf("\t%-20s\t\t%s\t\n", yytext, "Error: Keyword is used as an identifier");
                 } else if (validate_identifier(arrName)) {
                     int size = atoi(sizeStr);
                     if (size > 0) {
                         printf("\t%-20s\t\t%s\t\n", yytext, "array declaration");
                         if (!isDeclared(arrName)) {
                             symbolTable[symbolCount++] = strdup(arrName);
                         }
                     } else {
                         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid array size");
                     }
                 } else {
                     printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid identifier");
                 }
             } else {  
                 printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
             }
             varDeclPos++;
         } else {
             printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid array declaration");
         }
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 275 "lexerpart1.l"
{
    if (varDeclPos == 0) { 
        if (isKeyword(yytext)) {
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: Keyword is used as an identifier");
        } else if (validate_identifier(yytext)) {
            if (!isDeclared(yytext)) {
                printf("\t%-20s\t\t%s\t\n", yytext, "Identifier");
                symbolTable[symbolCount++] = strdup(yytext);
            } else {
                printf("\t%-20s\t\t%s\t\n", yytext, "Error: identifier already declared");
            }
        } else {
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid identifier");
        }
    } else if (varDeclPos == 1) {  
        if (strcmp(yytext, "int") == 0 || strcmp(yytext, "char") == 0) {
            printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
        } else {
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid datatype");
        }
    } else {
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unexpected token in VarDecl");
    }
    varDeclPos++;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 300 "lexerpart1.l"
{
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid token in VarDecl");
    }
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 305 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Keyword");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 309 "lexerpart1.l"
{
    reset_print_buffers();
    BEGIN(PRINT);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 314 "lexerpart1.l"
{
    reset_scan_buffers();
    BEGIN(SCAN);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 319 "lexerpart1.l"
{
    if (validate_identifier(yytext)) {
        if (isDeclared(yytext))
            printf("\t%-20s\t\t%s\t\n", yytext, "Identifier");
        else 
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: undefined identifier");
    }
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 328 "lexerpart1.l"
{
    //printf("\t%-20s\t\t%s\t\n", yytext, "Comment");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 332 "lexerpart1.l"
{
    BEGIN(COMMENT);
    comment_index = 0;
    comment_buffer[0] = '\0';
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 338 "lexerpart1.l"
{
    //printf("\t%-20s\t\t%s\t\n", comment_buffer, "Comment");
    BEGIN(INITIAL);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 343 "lexerpart1.l"
{
    if (comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = '\n';
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 350 "lexerpart1.l"
{
    if (comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = yytext[0];
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 358 "lexerpart1.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    int value_len = (int)(strchr(yytext, ',') - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_binary(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 371 "lexerpart1.l"
{
    char tmp[128];
    char *start = yytext + 1; 
    while (*start == ' ' || *start == '\t') 
        start++;
    char *comma_ptr = strchr(start, ','); 
    int value_len = (int)(comma_ptr - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_octal(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 386 "lexerpart1.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') 
        start++;
    char *comma_ptr = strchr(start, ',');  
    int value_len = (int)(comma_ptr - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_decimal(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 401 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 405 "lexerpart1.l"
{
    if (validate_char_const(yytext))
         printf("\t%-20s\t\t%s\t\n", yytext, "Character constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid character constant");
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 412 "lexerpart1.l"
{ 
    if (parentheses_count > 1) {
         printf("\t%-20s\t\t%s\t\n", "(", "Error: parenthesis count exceeds 1");
    }
    parentheses_count++;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 419 "lexerpart1.l"
{ BEGIN(STRING); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 421 "lexerpart1.l"
{ 
    strncat(print_string, yytext, sizeof(print_string)-strlen(print_string)-1);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 425 "lexerpart1.l"
{
     print_state_string_captured = 1;
     count_at_symbols(print_string);
     BEGIN(PRINT);
}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 431 "lexerpart1.l"
{ 
    char temp[1204];
    snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    printf("\t%-20s\t\t%s\t\n", temp, "Error: Invalid output statement");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 439 "lexerpart1.l"
{}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 441 "lexerpart1.l"
{
    arg_count++;
}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 445 "lexerpart1.l"
{
    arg_count++;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 449 "lexerpart1.l"
{
    if (!isDeclared(yytext)) {
         if(print_args[0] != '\0')
              strncat(print_args, ", ", sizeof(print_args)-strlen(print_args)-1);
         strncat(print_args, yytext, sizeof(print_args)-strlen(print_args)-1);
    } else {
         if(print_args[0] != '\0')
              strncat(print_args, ", ", sizeof(print_args)-strlen(print_args)-1);
         strncat(print_args, yytext, sizeof(print_args)-strlen(print_args)-1);
    }
    arg_count++;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 462 "lexerpart1.l"
{
    if (parentheses_count > 1)
        printf("\t%-20s\t\t%s\t\n", ")", "Error: parenthesis count exceeds 1");
    if (parentheses_count > 0)
        parentheses_count--;
    else
        printf("\t%-20s\t\t%s\t\n", ")", "Error: unmatched closing parenthesis");
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 471 "lexerpart1.l"
{
    if (parentheses_count != 0)
        printf("\t%-20s\t\t%s\t\n", ";", "Error: parentheses not closed");
    else
        finalize_print_statement();
    BEGIN(INITIAL);
}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 479 "lexerpart1.l"
{ 
    char temp[1204];
    snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    if (parentheses_count != 0)
         printf("\t%-20s\t\t%s\t\n", temp, "Error: missing closing parenthesis and semicolon");
    else
         printf("\t%-20s\t\t%s\t\n", temp, "Error: missing semicolon");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 490 "lexerpart1.l"
{scan_paranthesis_count++;}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 491 "lexerpart1.l"
{ strncpy(scan_string,yytext,yyleng);
                    scan_string[yyleng] = '\0';
                    count_all_symbols(scan_string);
                     }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 495 "lexerpart1.l"
{ scan_arg_count++;}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 497 "lexerpart1.l"
{ scan_arg_count++; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 498 "lexerpart1.l"
{ 
    scan_arg_count++;
    if(!validate_identifier(yytext))
         scan_fl = 1;
    else
         scan_fl = (!isDeclared(yytext))?1:scan_fl; 
    if(scan_args[0] != '\0')
         strncat(scan_args, ", ", sizeof(scan_args)-strlen(scan_args)-1);
    strncat(scan_args, yytext, sizeof(scan_args)-strlen(scan_args)-1);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 508 "lexerpart1.l"
{scan_paranthesis_count--;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 509 "lexerpart1.l"
{
    char temp[1204];
    snprintf(temp, sizeof(temp), "scan(%s, %s);", scan_string, scan_args);
    if (!validate_scan_placeholders(scan_string))
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else if (scan_paranthesis_count != 0)
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else if (scan_arg_count != scan_symbol_count)
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else
         printf("\t%-20s\t\t%s\t\n", temp, "Valid input statement");
    BEGIN(INITIAL);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 522 "lexerpart1.l"
{}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 523 "lexerpart1.l"
{
            printf("Error: invalid input statement\n"); 
            BEGIN(INITIAL); 
        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 528 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 532 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Arithmetic operator");
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 536 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Relational operator");
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 540 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Assignment operator");
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 544 "lexerpart1.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Separator");
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 548 "lexerpart1.l"
{}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 550 "lexerpart1.l"
{
    if(YYSTATE == PRINT)
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unexpected token");
    else
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unknown token");
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 557 "lexerpart1.l"
ECHO;
	YY_BREAK
#line 1677 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(VARDECL):
case YY_STATE_EOF(NUMRELATIONS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(PRINT):
case YY_STATE_EOF(CONDITION):
case YY_STATE_EOF(SCAN):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 202 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 202 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 201);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 557 "lexerpart1.l"


int main(int argc, char **argv) {
    FILE *file = fopen("t1.txt", "r");
     if (!file) {
        printf("File Not Found");
        exit(1);
    }
    yyin = file;
    printf("\t%-20s\t\t%s\t\n", "LEXEME", "TOKEN TYPE");
    yylex();
    fclose(file);
    return 0;
}

int yywrap(){
    return 1;
}
