
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[259] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       92,   90,   88,   89,   90,   47,   90,   40,   41,   45,
       43,   42,   44,   46,   10,   39,   50,   48,   49,   90,
       90,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   23,   24,   15,   16,
       17,   23,   91,   18,   23,   23,   22,   22,   22,   22,
       63,   64,   74,   72,   73,   62,   74,   61,   70,   65,
       71,   74,   66,   91,   76,   81,   78,   82,   91,   79,
       88,    0,   87,    0,   59,    0,    0,    0,    0,   57,
       55,   56,    4,    3,   58,   54,   52,   53,   51,    0,

        0,    0,   83,   83,   83,   83,   83,   29,   83,   83,
       83,   25,   83,   83,   83,   36,   83,   83,   30,   83,
       23,   24,   23,   13,    0,   23,   23,    0,   22,    0,
       22,   22,   22,   63,   72,    0,    0,    0,    0,    0,
        0,   66,    0,   77,    0,    0,   79,   86,    0,    0,
        0,    0,    3,    0,    0,   37,   83,   83,   32,   83,
        7,   28,   31,   34,   83,   38,   83,   83,   83,   83,
       23,    0,   23,   13,   13,    0,    0,   22,   11,   19,
       69,    0,   69,    0,    0,    0,    0,    0,    0,    0,
        2,   84,    0,   83,   35,   26,   33,   83,   83,   75,

       83,    0,   12,   21,    0,   20,    0,    0,    0,   67,
       80,    0,    1,    0,    6,   60,   83,   27,   12,    0,
        0,   68,    0,    0,    0,   83,   83,    0,    9,    0,
        0,    0,   83,    8,   14,    0,    0,    0,   83,    0,
        0,    0,   83,    0,    0,    0,   83,    0,    0,    0,
       83,    0,    0,    5,    5,    5,    5,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        8,    9,   10,   11,   12,    1,   13,   14,   15,   16,
       17,   17,   17,   17,   17,   18,   17,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   25,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   26,   24,   24,   24,   24,
       27,   28,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   40,   41,   42,   43,
       44,   45,   40,   46,   47,   48,   40,   40,   49,   40,
       40,   40,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    3,    4,    1,    5,    2,    2,    1,    1,
        2,    1,    1,    6,    6,    6,    6,    6,    1,    2,
        1,    1,    1,    7,    7,    7,    7,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6
    } ;

static const flex_int16_t yy_base[279] =
    {   0,
        0,    0,   49,    0,  854,  846,   98,    0,  147,    0,
      843,  913,  838,  913,  193,  817,  803,  196,  913,  807,
      800,  913,  788,  193,  787,  913,  177,  913,  786,  780,
      174,  192,  198,  202,  212,  207,  197,  199,  209,  223,
      211,  222,  225,  226,  228,  238,    0,  201,  913,  913,
      913,  265,  913,  913,  282,  775,  308,  312,  316,  320,
        0,  913,  913,  803,  913,  913,  776,  350,  913,  913,
      913,  775,  329,  797,  913,  913,  913,  913,  772,  345,
      794,  203,  913,    0,  913,  202,  788,  359,  376,  913,
      913,  913,  784,    0,  913,  913,  913,  913,  913,  765,

      365,  235,  240,  245,  314,  353,  363,  258,  313,  351,
      364,  365,  368,  367,  369,  370,  380,  387,  385,  386,
        0,  262,  431,  460,  763,    0,  431,  396,  450,  476,
      471,  479,  483,    0,  752,  472,  508,  510,  527,  709,
      501,  496,  710,  913,  686,  532,  508,  913,  460,  537,
      688,  425,    0,  542,  401,  526,  528,  529,  530,  533,
      534,  541,  544,  545,  547,  548,  551,  561,  558,  562,
      606,  685,  679,  635,    0,  651,  474,  596,  625,  646,
      913,  534,  581,  671,  597,  673,  667,  686,  691,  708,
      913,  913,  250,  643,  569,  582,  602,  683,  684,  676,

      677,  454,    0,  913,  663,  708,  727,  665,  425,  913,
      913,  736,  913,  713,  715,  704,  718,  712,  913,  724,
      750,  913,  573,  735,  736,  720,  730,  597,  616,  553,
      535,  649,  733,  734,  539,  491,  486,  628,  738,  455,
      431,  744,  741,  416,  393,  756,  753,  356,  331,  754,
      756,  249,  207,  784,  768,  218,  207,  913,  812,  819,
      826,  828,  830,  837,  839,  846,  853,  855,  857,  864,
      866,  868,  875,  882,  889,  896,  898,  905
    } ;

static const flex_int16_t yy_def[279] =
    {   0,
      258,    1,  258,    3,  259,  259,  258,    7,  258,    9,
      258,  258,  258,  258,  260,  258,  261,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  262,
      262,  263,  263,  263,  263,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,  264,  258,  258,  258,
      258,  264,  258,  258,  258,   55,  265,  265,  265,  265,
      266,  258,  258,  258,  258,  258,  267,  258,  258,  258,
      258,  268,  269,  270,  258,  258,  258,  258,  271,  272,
      258,  260,  258,  260,  258,  261,  261,  258,  258,  258,
      258,  258,  273,  274,  258,  258,  258,  258,  258,  262,

      258,  262,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      264,  258,  275,  276,  277,   55,  264,  277,  265,  258,
      265,  265,  265,  266,  258,  267,  278,  258,  258,  268,
      258,  269,  270,  258,  271,  258,  272,  258,  258,  258,
      273,  273,  274,  258,  262,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
      275,  275,  171,  276,  276,  258,  277,  265,  265,  265,
      258,  267,  267,  278,  258,  258,  258,  258,  258,  258,
      258,  258,  262,   35,   35,   35,   35,   35,   35,   35,

       35,  275,  264,  258,  277,  265,  258,  258,  258,  258,
      258,  258,  258,  262,   35,   35,   35,   35,  258,  277,
      258,  258,  262,  258,  262,   35,   35,  277,  262,  258,
      258,  262,   35,   35,  277,  258,  258,  262,   35,  258,
      258,  262,   35,  258,  258,  262,   35,  258,  258,  262,
       35,  258,  258,  262,   35,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258
    } ;

static const flex_int16_t yy_nxt[963] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   12,   12,   12,   12,   12,   25,   26,
       27,   28,   29,   30,   30,   31,   12,   12,   12,   12,
       32,   33,   34,   35,   36,   37,   38,   38,   39,   38,
       38,   40,   41,   42,   43,   38,   44,   45,   46,   47,
       48,   48,   47,   47,   47,   49,   50,   47,   47,   51,
       47,   52,   53,   53,   53,   53,   53,   47,   54,   47,
       47,   47,   55,   55,   56,   47,   47,   47,   53,   57,
       57,   58,   57,   59,   57,   57,   57,   60,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   63,   64,

       65,   66,   63,   67,   68,   69,   63,   63,   70,   63,
       63,   63,   63,   63,   63,   63,   63,   71,   63,   63,
       63,   72,   72,   72,   63,   63,   63,   63,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   53,   53,   53,
       74,   53,   53,   75,   76,   53,   53,   77,   53,   53,
       53,   53,   53,   53,   53,   53,   78,   53,   53,   53,
       79,   79,   79,   53,   53,   53,   53,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   83,   88,   97,   98,

      101,   93,  122,  122,  102,   94,   83,  148,  257,   89,
       89,   89,   89,   89,   95,  100,  100,  100,  101,  257,
       84,  100,  100,  100,  101,  100,  100,  100,  101,   87,
       84,  103,  105,  103,  104,  100,  100,  100,  101,  106,
      111,  103,  103,  103,  112,  103,  107,  109,  256,  110,
      103,  113,  103,  114,  115,  108,  103,  103,  118,  103,
      103,  101,  103,  122,  122,  103,  103,  116,  103,  103,
      117,  119,  103,  123,  103,  120,  101,  124,  156,  103,
      155,  103,  121,  103,  214,  121,  121,  121,  103,  256,
      121,  121,  103,  121,  121,  125,  125,  125,  125,  125,

      121,  103,  121,  121,  121,  126,  126,  126,  127,  121,
      121,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  130,  125,  125,  125,  130,  125,
      125,  125,  130,  125,  125,  125,  130,  103,  103,  131,
      157,  138,  140,  140,  140,  141,  103,  103,  132,  160,
       88,  253,  133,  139,  139,  139,  139,  139,  145,  145,
      145,  146,   89,   89,   89,   89,   89,  149,  154,  154,
      154,  154,  154,  158,  161,  103,  150,  103,  252,   89,
       89,   89,   89,   89,  103,  159,  103,  103,  103,  103,

      163,  103,  103,  103,  103,  165,  103,  103,  103,  162,
      103,  103,  103,  103,  103,  164,  166,  169,  167,  103,
      103,  103,  130,  168,  170,  193,  221,  101,  103,  103,
      103,  171,  222,  152,  171,  171,  171,  191,  249,  173,
      171,  177,  171,  171,  176,  176,  176,  176,  176,  171,
      248,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      174,  149,  202,  174,  174,  174,  219,  245,  174,  174,
      150,  174,  174,  125,  125,  125,  130,  181,  174,  244,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  176,
      176,  176,  176,  176,  125,  125,  125,  130,  205,  137,

      130,  178,  125,  125,  125,  130,  125,  125,  125,  130,
      136,  138,  179,  183,  187,  187,  187,  187,  187,  140,
      140,  140,  141,  139,  139,  139,  139,  139,  185,  241,
      180,  145,  145,  145,  146,  184,  240,  186,  189,  181,
      139,  139,  139,  139,  139,  188,  188,  188,  188,  188,
      190,  190,  190,  190,  190,  154,  154,  154,  154,  154,
      103,  137,  103,  103,  103,  130,  194,  196,  103,  103,
      192,  103,  103,  103,  195,  103,  103,  103,  103,  103,
      237,  103,  103,  236,  103,  103,  181,  103,  103,  197,
      103,  103,  103,  198,  103,  103,  103,  199,  185,  101,

      200,  103,  201,  103,  103,  103,  171,  186,  137,  171,
      171,  171,  103,  229,  173,  171,  103,  171,  171,  125,
      125,  125,  130,  130,  171,  103,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  174,  103,  235,  174,  174,
      174,  206,  101,  174,  174,  103,  174,  174,  125,  125,
      125,  130,  242,  174,  101,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  176,  176,  176,  176,  176,  125,
      125,  125,  130,  136,  207,  101,  183,  103,  209,  204,
      187,  187,  187,  187,  187,  215,  103,  208,  209,  130,
      209,  203,  189,  202,  238,  210,  152,  220,  184,  188,

      188,  188,  188,  188,  190,  190,  190,  190,  190,  212,
      103,  218,  146,  144,  211,  213,  224,  103,  103,  103,
      103,  190,  190,  190,  190,  190,  103,  103,  207,  217,
      216,  125,  125,  125,  130,  141,  224,  212,  103,  101,
      225,  208,  209,  213,  209,  223,  103,  103,  227,  103,
      130,  221,  103,  135,  103,  103,  228,  222,  103,  226,
      230,  103,  101,  103,  103,  233,  232,  103,  103,  257,
      101,  234,  103,  103,  243,  103,  239,  103,  246,  231,
      101,  103,  101,  251,  103,  257,  247,  103,  250,  130,
      103,  101,  152,   86,  254,   81,  103,  255,  146,  103,

      144,  141,  103,  137,  135,  128,  101,   99,   96,   92,
      101,  103,   61,   61,   61,   61,   61,   61,   61,   82,
       82,   91,   82,   82,   82,   82,   86,   86,   90,   86,
       87,   86,   86,  100,  100,  103,  103,  121,   85,   81,
      121,  121,  258,  121,  129,  129,  134,  134,  134,   62,
      134,  134,  134,  136,  136,  136,  136,   62,  136,  136,
      140,  140,  142,  142,  143,  143,  143,  143,  143,  143,
      143,  145,  145,  147,  147,  151,  151,  151,  151,  151,
      151,  151,  153,  153,  258,  153,  153,  153,  153,  172,
      172,  172,  172,  172,  172,  172,  175,  175,  258,  175,

      175,  175,  175,  125,  125,  182,  182,  182,  182,  182,
      182,  182,   11,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258
    } ;

static const flex_int16_t yy_chk[963] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   15,   18,   27,   27,

       31,   24,   48,   48,   31,   24,   82,   86,  257,   18,
       18,   18,   18,   18,   24,   32,   32,   32,   32,  256,
       15,   33,   33,   33,   33,   34,   34,   34,   34,   86,
       82,   37,   33,   38,   32,   35,   35,   35,   35,   34,
       37,   36,   38,   39,   39,   41,   35,   36,  253,   36,
       36,   39,   39,   40,   41,   35,   42,   40,   44,   43,
       44,  102,   45,  122,  122,   42,   40,   42,   43,   44,
       43,   45,   46,   52,  103,   46,  193,   52,  104,  104,
      102,   46,   55,  103,  193,   55,   55,   55,  104,  252,
       55,   55,  108,   55,   55,   55,   55,   55,   55,   55,

       55,  108,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   57,   57,   57,   57,   58,   58,   58,   58,   59,
       59,   59,   59,   60,   60,   60,   60,  109,  105,   58,
      105,   68,   73,   73,   73,   73,  109,  105,   59,  109,
       88,  249,   60,   68,   68,   68,   68,   68,   80,   80,
       80,   80,   88,   88,   88,   88,   88,   89,  101,  101,
      101,  101,  101,  106,  110,  110,   89,  106,  248,   89,
       89,   89,   89,   89,  110,  107,  106,  107,  111,  112,

      113,  114,  113,  115,  116,  114,  107,  111,  112,  111,
      114,  113,  115,  116,  117,  113,  115,  118,  117,  119,
      120,  118,  128,  117,  120,  155,  209,  155,  119,  120,
      118,  123,  209,  152,  123,  123,  123,  152,  245,  123,
      123,  128,  123,  123,  127,  127,  127,  127,  127,  123,
      244,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      124,  149,  202,  124,  124,  124,  202,  241,  124,  124,
      149,  124,  124,  129,  129,  129,  129,  136,  124,  240,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  130,
      130,  130,  130,  130,  131,  131,  131,  131,  177,  136,

      177,  131,  132,  132,  132,  132,  133,  133,  133,  133,
      137,  138,  132,  137,  141,  141,  141,  141,  141,  142,
      142,  142,  142,  138,  138,  138,  138,  138,  139,  237,
      133,  147,  147,  147,  147,  137,  236,  139,  150,  182,
      139,  139,  139,  139,  139,  146,  146,  146,  146,  146,
      150,  150,  150,  150,  150,  154,  154,  154,  154,  154,
      156,  182,  157,  158,  159,  235,  157,  160,  161,  156,
      154,  157,  158,  159,  158,  162,  160,  161,  163,  164,
      231,  165,  166,  230,  162,  167,  183,  163,  164,  165,
      165,  166,  169,  167,  167,  168,  170,  168,  185,  223,

      169,  169,  170,  195,  168,  170,  171,  185,  183,  171,
      171,  171,  195,  223,  171,  171,  196,  171,  171,  178,
      178,  178,  178,  228,  171,  196,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  174,  197,  228,  174,  174,
      174,  178,  229,  174,  174,  197,  174,  174,  179,  179,
      179,  179,  238,  174,  238,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  176,  176,  176,  176,  176,  180,
      180,  180,  180,  184,  186,  232,  184,  194,  208,  176,
      187,  187,  187,  187,  187,  194,  194,  186,  186,  205,
      186,  173,  189,  172,  232,  187,  151,  205,  184,  188,

      188,  188,  188,  188,  189,  189,  189,  189,  189,  190,
      200,  201,  145,  143,  188,  190,  215,  198,  199,  200,
      201,  190,  190,  190,  190,  190,  198,  199,  207,  199,
      198,  206,  206,  206,  206,  140,  224,  212,  216,  214,
      215,  207,  207,  212,  207,  214,  218,  216,  217,  215,
      220,  221,  217,  135,  226,  218,  220,  221,  215,  215,
      224,  217,  225,  226,  227,  226,  225,  233,  234,  255,
      242,  227,  239,  227,  239,  243,  233,  234,  242,  224,
      250,  239,  246,  247,  243,  254,  243,  247,  246,  125,
      251,  100,   93,   87,  250,   81,  247,  251,   79,  251,

       74,   72,  255,   67,   64,   56,   30,   29,   25,   23,
      254,  255,  259,  259,  259,  259,  259,  259,  259,  260,
      260,   21,  260,  260,  260,  260,  261,  261,   20,  261,
       17,  261,  261,  262,  262,  263,  263,  264,   16,   13,
      264,  264,   11,  264,  265,  265,  266,  266,  266,    6,
      266,  266,  266,  267,  267,  267,  267,    5,  267,  267,
      268,  268,  269,  269,  270,  270,  270,  270,  270,  270,
      270,  271,  271,  272,  272,  273,  273,  273,  273,  273,
      273,  273,  274,  274,    0,  274,  274,  274,  274,  275,
      275,  275,  275,  275,  275,  275,  276,  276,    0,  276,

      276,  276,  276,  277,  277,  278,  278,  278,  278,  278,
      278,  278,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[92] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "threeac.l"
#line 2 "threeac.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "threeac.tab.h"
#define MAX_COMMENT_SIZE 2048
static char comment_buffer[MAX_COMMENT_SIZE];
static int comment_index = 0;
static char scan_args[1024];
static char print_string[1024];
static char print_args[1024];
static int print_state_string_captured = 0;
static int at_count = 0;
static int arg_count = 0;
static int parentheses_count = 0;
static int varDeclPos = 0;
char* symbolTable[256];
int symbolCount = 0;
static int varDeclFlag = 0;
int suppress_lexer_output = 1;
extern int print_lexeme_token_pairs;
void print_token(const char *lexeme, const char *token_type) {
    if(print_lexeme_token_pairs && !suppress_lexer_output)
        fprintf(stderr, "%-20s  %-20s\n", lexeme, token_type);
}
char* strdup_safe(const char *s) {
    char* dup = (char*)malloc(strlen(s)+1);
    if(dup) strcpy(dup, s);
    return dup;
}
int isDeclared(const char *id) {
    int i;
    for(i=0; i<symbolCount; i++){
        if(strcmp(symbolTable[i], id)==0)
            return 1;
    }
    return 0;
}
void reset_print_buffers() {
    memset(print_string, 0, sizeof(print_string));
    memset(print_args, 0, sizeof(print_args));
    print_state_string_captured = 0;
    at_count = 0;
    arg_count = 0;
    parentheses_count = 0;
}
void count_at_symbols(const char *s) {
    int i;
    for(i=0; s[i]; i++){
        if(s[i]=='@') at_count++;
    }
}
void finalize_print_statement() {
    char temp[1204];
    if(strlen(print_args)>0)
         snprintf(temp, sizeof(temp), "print(\"%s\", %s);", print_string, print_args);
    else
         snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
}
int validate_identifier(const char *text) {
    const char *keywords[] = {"int","char","if","else","while","for","main","begin","end","print","scan","program","VarDecl","inc","dec","to","do",NULL};
    int i; for(i=0; keywords[i]!=NULL; i++){ if(strcmp(text,keywords[i])==0)return 0; }
    if(text[0] < 'a' || text[0] > 'z') return 0;
    { int underscore=0,j; for(j=0; text[j]!='\0'; j++){
         if(text[j]=='_'){ underscore++; if(underscore>1)return 0; }
         else if(!(text[j]>='a' && text[j]<='z') && !(text[j]>='0' && text[j]<='9'))
            return 0;
       } }
    return 1;
}
int validate_char_const(const char *text) {
    int len = strlen(text);
    if(len<3)return 0;
    if(text[0]=='\'' && text[len-1]=='\'')
         return 1;
    return 0;
}
int validate_decimal(const char *text) {
    int i; for(i=0; text[i]!='\0'; i++){ if(text[i]<'0' || text[i]>'9') return 0; } return 1;
}
int validate_octal(const char *text) {
    int i; for(i=0; text[i]!='\0'; i++){ if(text[i]<'0' || text[i]>'7') return 0; } return 1;
}
int validate_binary(const char *text) {
    int i; for(i=0; text[i]!='\0'; i++){ if(text[i]!='0' && text[i]!='1') return 0; } return 1;
}
int scan_arg_count=0;
int scan_paranthesis_count=0;
int scan_symbol_count=0;
int scan_fl=0;
char scan_string[1024];
void reset_scan_buffers(){
    scan_arg_count=0;
    scan_paranthesis_count=0;
    scan_symbol_count=0;
    scan_fl=0;
    scan_string[0]='\0';
    scan_args[0]='\0';
}
void count_all_symbols(char* str){
    int idx=0;
    while(str[idx]!='\0'){
        if(str[idx]=='@')
            scan_symbol_count++;
        idx++;
    }
}
int validate_scan_placeholders(const char *s) {
    int atCount=0, commaCount=0, i;
    int len=strlen(s), start=0, end=len;
    if(len>=2 && s[0]=='\"' && s[len-1]=='\"'){
        start=1; end=len-1;
    }
    for(i=start;i<end;i++){
         if(s[i]=='\"')
             return 0;
         if(s[i]=='@')
             atCount++;
         else if(s[i]==',')
             commaCount++;
    } 
    if(atCount < 1 || commaCount != atCount-1)return 0;
    return 1;
}
int statement_fl=0;
int isKeyword(const char *word) {
    const char *keywords[] = {"begin","end","VarDecl","int","char","if","else","while","for","print","scan","program","inc","dec","do","to","main",NULL};
    int i; for(i=0; keywords[i]!=NULL; i++){ if(strcmp(word,keywords[i])==0)return 1; } return 0;
}
#line 900 "lex.yy.c"

#line 902 "lex.yy.c"

#define INITIAL 0
#define VARDECL 1
#define STRING 2
#define PRINT 3
#define SCAN 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 133 "threeac.l"

#line 1125 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 913 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 134 "threeac.l"
{ yylval.str = strdup_safe(yytext); return INTEGER_CONST; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 135 "threeac.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 136 "threeac.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 137 "threeac.l"
{ }
	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 138 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_BEGIN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 139 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_BLOCKBEGIN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 140 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_END; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 141 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_PROGRAM; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 142 "threeac.l"
{ print_token(yytext, "KEYWORD"); varDeclFlag = 1; return TK_VARDECL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 143 "threeac.l"
{ print_token(yytext, "SEPARATOR"); if(varDeclFlag){ varDeclFlag=0; BEGIN(VARDECL); } return TK_COLON; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 "threeac.l"
{ print_token(yytext, "KEYWORD"); BEGIN(INITIAL); return TK_END; }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 145 "threeac.l"
{ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "threeac.l"
{ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 147 "threeac.l"
{ print_token(yytext, "KEYWORD"); BEGIN(INITIAL); return TK_VARDECL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 148 "threeac.l"
{ print_token(yytext, "SEPARATOR"); varDeclPos=0; return LPAREN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 149 "threeac.l"
{ print_token(yytext, "SEPARATOR"); return RPAREN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 150 "threeac.l"
{ print_token(yytext, "SEPARATOR"); varDeclPos++; return COMMA; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 151 "threeac.l"
{ print_token(yytext, "SEPARATOR"); varDeclPos=0; return TK_SEP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 152 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_INT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 153 "threeac.l"
{ print_token(yytext, "KEYWORD"); return TK_CHAR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 154 "threeac.l"
{
  char arrName[256], sizeStr[64];
  if(sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr)==2) {
    if(varDeclPos==0) {
      if(isKeyword(arrName))
         print_token(yytext, "Error: Keyword used as identifier");
      else if(validate_identifier(arrName)){
         int size = atoi(sizeStr);
         if(size>0){
           print_token(yytext, "array declaration");
           yylval.str = strdup_safe(yytext);
           if(!isDeclared(arrName))
             symbolTable[symbolCount++] = strdup_safe(arrName);
           return IDENTIFIER;
         } else { print_token(yytext, "Error: invalid array size"); }
      } else { print_token(yytext, "Error: invalid identifier"); }
    } else { print_token(yytext, "keyword"); }
    varDeclPos++;
  } else { print_token(yytext, "Error: invalid array declaration"); }
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 174 "threeac.l"
{
    if(varDeclPos==0) {
      if(!validate_identifier(yytext))
         print_token(yytext, "ERROR: Invalid identifier");
      else if(isDeclared(yytext))
         print_token(yytext, "ERROR: Identifier already declared");
      else {
         print_token(yytext, "IDENTIFIER");
         symbolTable[symbolCount++] = strdup_safe(yytext);
      }
    } else if(varDeclPos==1)
         print_token(yytext, "ERROR: Invalid data type");
    yylval.str = strdup_safe(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 189 "threeac.l"
{ print_token(yytext, "ERROR: Invalid token in VarDecl"); return yytext[0]; }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 190 "threeac.l"
{ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 191 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_IF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 192 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 193 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_WHILE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 194 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_FOR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 195 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_DO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 196 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_TO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 197 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_INC; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 198 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_DEC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 199 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_MAIN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 200 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_INT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 201 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return TK_CHAR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 202 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return OR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 203 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return AND; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 204 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "KEYWORD"); return NOT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 205 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "SEPARATOR"); return TK_SEP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 206 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "SEPARATOR"); return LPAREN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 207 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "SEPARATOR"); return RPAREN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 208 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "SEPARATOR"); return COMMA; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 209 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return PLUS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 210 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MINUS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 211 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MULT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 212 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return DIV; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 213 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MOD; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 214 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return EQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 215 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return GT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 216 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return LT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 217 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return GE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 218 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return LE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 219 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return NE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 220 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "Assignment operator"); return ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 221 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return PLUS_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 222 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MINUS_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 223 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MULT_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 224 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return DIV_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 225 "threeac.l"
{yylval.str = strdup_safe(yytext); print_token(yytext, "OPERATOR"); return MOD_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 226 "threeac.l"
{ print_token(yytext, "KEYWORD"); reset_print_buffers(); BEGIN(PRINT); return TK_PRINT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 227 "threeac.l"
{ print_token(yytext, "SEPARATOR"); parentheses_count++; return LPAREN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 228 "threeac.l"
{ BEGIN(STRING); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 229 "threeac.l"
{ strncat(print_string, yytext, sizeof(print_string)-strlen(print_string)-1); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 230 "threeac.l"
{ print_state_string_captured = 1; count_at_symbols(print_string); BEGIN(PRINT); yylval.str = strdup_safe(print_string); return STRING_LITERAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 231 "threeac.l"
{ print_token(yytext, "SEPARATOR"); return COMMA; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 232 "threeac.l"
{
    print_token(yytext, "IDENTIFIER");
    arg_count++;
    if(strlen(print_args)>0)
         strncat(print_args, ", ", sizeof(print_args)-strlen(print_args)-1);
    strncat(print_args, yytext, sizeof(print_args)-strlen(print_args)-1);
    yylval.str = strdup_safe(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 241 "threeac.l"
{
  char arrName[256], sizeStr[64];
  if(sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr)==2) {
    if(varDeclPos==0) {
      if(isKeyword(arrName))
         print_token(yytext, "Error: Keyword used as identifier");
      else if(validate_identifier(yytext)) {
         int size = atoi(sizeStr);
         if(size>0) { print_token(yytext, "array declaration"); yylval.str = strdup_safe(yytext); return IDENTIFIER; }
         else print_token(yytext, "Error: invalid array size");
      } else print_token(yytext, "Error: invalid identifier");
    } else { print_token(yytext, "keyword"); }
    varDeclPos++;
  } else { print_token(yytext, "Error: invalid array declaration"); }
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 256 "threeac.l"
{
    print_token(yytext, "INTEGER_CONST");
    arg_count++;
    yylval.str = strdup_safe(yytext);
    return INTEGER_CONST;
}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 262 "threeac.l"
{
    print_token(yytext, "CHARACTER_CONST");
    arg_count++;
    yylval.str = strdup_safe(yytext);
    return CHAR_CONST;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 268 "threeac.l"
{ print_token(yytext, "SEPARATOR"); parentheses_count--; return RPAREN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 269 "threeac.l"
{ print_token(yytext, "SEPARATOR"); finalize_print_statement(); BEGIN(INITIAL); return TK_SEP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 270 "threeac.l"
{ }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 271 "threeac.l"
{ }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 272 "threeac.l"
{ print_token(yytext, "ERROR: unexpected character in print statement"); return yytext[0]; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 273 "threeac.l"
{ print_token(yytext, "KEYWORD"); reset_scan_buffers(); BEGIN(SCAN); return TK_SCAN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 274 "threeac.l"
{ print_token(yytext, "SEPARATOR"); scan_paranthesis_count++; return LPAREN; }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 275 "threeac.l"
{
    print_token(yytext, "STRING_LITERAL");
    strncpy(scan_string, yytext, yyleng);
    scan_string[yyleng] = '\0';
    count_all_symbols(scan_string);
    yylval.str = strdup_safe(yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 283 "threeac.l"
{ print_token(yytext, "SEPARATOR"); return COMMA; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 284 "threeac.l"
{
    print_token(yytext, "IDENTIFIER");
    scan_arg_count++;
    if(!validate_identifier(yytext))
         scan_fl = 1;
    else
         scan_fl = (!isDeclared(yytext)) ? 1 : scan_fl;
    if(strlen(scan_args)>0)
         strncat(scan_args, ", ", sizeof(scan_args)-strlen(scan_args)-1);
    strncat(scan_args, yytext, sizeof(scan_args)-strlen(scan_args)-1);
    yylval.str = strdup_safe(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 297 "threeac.l"
{
  char arrName[256], sizeStr[64];
  if(sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr)==2) {
    if(varDeclPos==0) {
      if(isKeyword(arrName))
         print_token(yytext, "Error: Keyword used as identifier");
      else if(validate_identifier(arrName)) {
         int size = atoi(sizeStr);
         if(size>0) { print_token(yytext, "array declaration"); yylval.str = strdup_safe(yytext); return IDENTIFIER; }
         else print_token(yytext, "Error: invalid array size");
      } else print_token(yytext, "Error: invalid identifier");
    } else { print_token(yytext, "keyword"); }
    varDeclPos++;
  } else { print_token(yytext, "Error: invalid array declaration"); }
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 312 "threeac.l"
{ print_token(yytext, "SEPARATOR"); scan_paranthesis_count--; return RPAREN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 313 "threeac.l"
{
    print_token(yytext, "SEPARATOR");
    { char temp[1204]; snprintf(temp, sizeof(temp), "scan(%s, %s);", scan_string, scan_args); }
    if(!validate_scan_placeholders(scan_string) || scan_paranthesis_count!=0 || scan_arg_count!=scan_symbol_count){}
    BEGIN(INITIAL);
    return TK_SEP;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 320 "threeac.l"
{
    if(validate_identifier(yytext))
         print_token(yytext, "IDENTIFIER");
    else print_token(yytext, "ERROR: Invalid identifier");
    yylval.str = strdup_safe(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 327 "threeac.l"
{
  char arrName[256], sizeStr[64];
  if(sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr)==2) {
    if(varDeclPos==0) {
      if(isKeyword(arrName))
         print_token(yytext, "Error: Keyword used as identifier");
      else if(validate_identifier(arrName)) {
         int size = atoi(sizeStr);
         if(size>0) { print_token(yytext, "array declaration"); yylval.str = strdup_safe(yytext); return IDENTIFIER; }
         else print_token(yytext, "Error: invalid array size");
      } else print_token(yytext, "Error: invalid identifier");
    } else { print_token(yytext, "keyword"); }
    varDeclPos++;
  } else { print_token(yytext, "Error: invalid array declaration"); }
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 342 "threeac.l"
{
    print_token(yytext, "ERROR: Invalid integer format");
    yylval.str = strdup_safe(yytext);
    return INTEGER_CONST;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 347 "threeac.l"
{
    print_token(yytext, (validate_char_const(yytext) ? "CHARACTER_CONST" : "ERROR: Invalid character constant"));
    yylval.str = strdup_safe(yytext);
    return CHAR_CONST;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 352 "threeac.l"
{
    print_token(yytext, "STRING_LITERAL");
    yylval.str = strdup_safe(yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 357 "threeac.l"
{ }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 358 "threeac.l"
{ }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 359 "threeac.l"
{ print_token(yytext, "ERROR: unexpected character"); return yytext[0]; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 360 "threeac.l"
ECHO;
	YY_BREAK
#line 1794 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(VARDECL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(PRINT):
case YY_STATE_EOF(SCAN):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 258);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 360 "threeac.l"

