
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[278] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,   66,    0,    0,    0,    0,    0,    0,    0,    0,
       83,   81,    2,   80,   76,   81,   79,   79,   76,   76,
       76,   76,   42,    4,   77,   77,   77,   75,   81,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   14,   82,    7,    8,    9,   14,   10,   13,   13,
       13,   38,   37,   38,   55,   45,   82,   44,   53,   49,
       54,   52,   66,   65,   67,   74,   82,   82,   82,   71,
       70,   69,   69,   69,   68,   27,   17,   17,   26,   27,
       25,   27,   22,   22,   22,   22,   22,   82,   64,   82,

       82,   56,   61,   63,   62,   60,   46,   48,   47,    2,
       80,   78,    0,    0,    0,    0,   35,   34,   42,   77,
        0,   33,   33,   33,   33,   33,   33,   33,   28,   33,
       33,   33,   33,   33,   33,   14,   11,   13,   14,   13,
       13,   36,    0,    0,    0,    0,   52,   66,    0,    0,
        0,   70,   69,   68,   17,    0,    0,   25,   23,   22,
       22,   21,   22,   18,   22,    0,   62,    0,   57,    0,
        0,    0,    0,   62,   60,   46,   43,    0,   43,    0,
        0,    0,   34,    0,   33,   33,   33,   28,   33,   33,
       33,   33,   33,   33,   11,   11,   14,   13,    5,   51,

        0,   51,    0,    0,    0,    0,   73,    0,    0,    0,
       20,   19,   22,   59,    0,   59,    0,    0,    0,    0,
        0,    0,    0,    0,   33,    0,   33,   33,   30,   33,
       12,   13,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,    0,    0,    0,   39,    0,   40,    0,
        1,    0,   29,   33,   31,   13,    0,   50,   72,   32,
        0,   24,   16,    0,   58,    0,   41,    0,    0,    0,
        0,   33,   13,    3,   15,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,    1,   14,   15,   16,   17,
       18,   18,   18,   18,   18,   19,   18,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   27,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   28,   26,   26,   26,   26,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   42,   43,   44,   45,
       46,   47,   42,   48,   49,   50,   42,   42,   51,   42,
       42,   42,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    2,    3,    2,    4,    1,    5,    6,    6,    1,
        1,    7,    1,    1,    8,    8,    8,    8,    8,    9,
        6,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   10,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    1,    1
    } ;

static const flex_int16_t yy_base[305] =
    {   0,
        0,    0,   53,    0,    0,    0,  104,  105,  113,    0,
      163,  165,  216,    0,  269,    0,  322,    0,  106,  107,
      939,  968,  124,  127,  911,  903,  172,  968,  909,  908,
      893,  109,  120,  892,  117,  968,  891,  968,  880,    0,
      872,  868,  870,   99,  860,   79,  852,  826,  834,  828,
      827,    0,  968,  968,  968,  968,  852,  968,  375,  428,
      100,  968,  968,  832,  968,  968,  815,  177,  968,  968,
      968,    0,  167,  175,  968,  968,  803,  787,  774,  968,
      188,  159,  968,  787,    0,  968,  206,  209,  968,  375,
      392,  783,    0,  341,  753,  743,  748,  399,  968,  780,

      754,  428,  968,  968,  410,    0,    0,  968,  968,  413,
      419,  968,  168,  433,  452,  460,  968,    0,  458,  968,
      730,    0,  738,  741,  738,  720,  725,  673,    0,  443,
      679,  139,  686,  681,  676,    0,  480,  683,  479,  452,
      450,  968,  389,  484,  500,  501,    0,  381,  676,  678,
      672,  491,  968,    0,  422,  518,  519,  509,  968,    0,
      677,    0,  676,    0,  669,  528,  536,  704,  968,  430,
      536,  540,  548,  543,    0,    0,  968,  534,  539,  558,
      566,  570,    0,  673,  656,  648,  646,  549,  634,  626,
      624,  613,  606,  595,  571,    0,  578,  422,  602,  968,

      541,  547,  560,  596,  597,  590,  968,  584,  600,  601,
        0,    0,  539,  968,  555,  577,  603,  617,  620,  624,
      561,  621,  640,  492,  467,  630,  461,  451,    0,  453,
        0,  578,  643,  464,  644,  421,  428,  648,  416,  652,
      381,  653,  398,  664,  672,  673,  968,  676,  968,  367,
        0,  682,    0,  182,    0,  654,  686,  968,  968,  968,
      689,  968,    0,  690,  968,  699,  968,  158,  702,  703,
      149,   99,  548,  968,  968,   80,  968,  723,  734,  745,
      756,  760,  771,  782,  793,  797,  801,  805,  816,  827,
      831,  842,  853,  863,  871,  882,  893,  903,  910,  918,

      928,  936,  946,  956
    } ;

static const flex_int16_t yy_def[305] =
    {   0,
      277,    1,  277,    3,  278,  278,  279,  279,  278,    9,
      278,  278,  277,   13,  277,   15,  277,   17,  280,  280,
      277,  277,  277,  277,  277,  281,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  283,  277,  277,  277,  277,  283,  277,  284,  284,
       60,  277,  277,  277,  277,  277,  285,  277,  277,  277,
      277,  286,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  287,  277,  277,  277,  277,  277,
      277,  277,  288,  288,  288,  288,  288,  277,  277,  289,

      290,  277,  277,  277,  277,  291,  292,  277,  277,  277,
      277,  277,  281,  293,  277,  294,  277,  295,  277,  277,
      277,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  283,  296,   60,  283,   60,
       60,  277,  285,  297,  277,  298,  286,  277,  277,  277,
      277,  277,  277,  287,  277,  277,  299,  277,  277,  288,
      288,  288,  288,  288,  288,  277,  277,  289,  277,  290,
      300,  277,  301,  277,  291,  292,  277,  281,  281,  293,
      277,  277,  295,  277,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  296,  302,  283,   60,   60,  277,

      285,  285,  297,  277,  277,  277,  277,  277,  277,  277,
      288,  288,  288,  277,  290,  290,  300,  277,  277,  277,
      277,  277,  277,  277,  282,  303,  282,  282,  282,  282,
      283,   60,  277,  277,  277,  277,  277,  277,  277,  277,
      288,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      282,  304,  282,  282,  282,   60,  277,  277,  277,  277,
      277,  277,  288,  277,  277,  277,  277,  277,  277,  304,
      277,  282,   60,  277,  277,   60,    0,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277
    } ;

static const flex_int16_t yy_nxt[1022] =
    {   0,
       22,   23,   24,   23,   22,   25,   26,   27,   28,   29,
       30,   28,   31,   32,   33,   33,   33,   33,   33,   34,
       28,   35,   36,   37,   38,   22,   22,   39,   22,   22,
       22,   22,   40,   41,   42,   43,   44,   45,   40,   40,
       46,   40,   40,   47,   40,   40,   48,   40,   49,   50,
       51,   28,   28,   52,   53,   53,   53,   52,   52,   52,
       54,   55,   52,   52,   56,   52,   57,   52,   52,   52,
       52,   52,   52,   58,   52,   52,   52,   52,   59,   59,
       60,   52,   52,   52,   52,   59,   59,   59,   59,   61,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   52,   52,   63,   63,  108,  108,
      109,  109,  138,   64,   64,   65,  129,   66,  117,   67,
       68,   69,  118,  130,   70,  110,  111,  110,  111,  111,
      111,  112,  138,   71,  119,  119,  119,  119,  119,  120,
      120,  126,  129,  127,  141,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   73,   74,   73,   74,  148,  148,
       75,  275,   75,  115,  177,  115,  148,  148,  145,  190,
      145,  153,  153,   76,  191,   76,  116,  116,  116,  116,
      116,  146,  146,  146,  146,  146,   77,  114,   77,   78,

      274,   78,  152,  152,  152,  152,  152,  155,  155,  155,
      155,  155,  155,   79,  272,   79,   53,   53,   53,   53,
       53,   53,   53,   53,   80,   53,   53,   53,   53,   53,
       81,   81,   81,   81,   81,   53,   53,   82,   83,   84,
       53,   53,   53,   53,   53,   53,   53,   53,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   53,   53,   86,
       87,   88,   87,   86,   89,   86,   90,   86,   89,   89,
       86,   89,   89,   91,   91,   91,   91,   91,   92,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   93,   93,   93,   94,   93,   93,   93,   93,   95,
       93,   93,   93,   93,   93,   93,   93,   93,   96,   97,
       86,   86,   53,   98,   99,   98,  100,   53,  101,  102,
      103,   53,   53,  104,   53,   53,   53,   53,   53,   53,
       53,   53,  105,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,   53,   53,  136,  156,  161,  156,  136,
      136,  136,  148,  148,  136,  136,  162,  136,  136,  157,
      157,  157,  157,  157,  136,  200,  136,  136,  136,  136,

      166,  268,  166,  139,  136,  136,  158,  158,  158,  158,
      158,  174,  244,  174,  110,  111,  110,  263,  144,  167,
      111,  111,  111,  155,  155,  155,  136,  136,  136,  172,
      240,  172,  136,  136,  136,  113,  214,  136,  136,  179,
      136,  136,  173,  173,  173,  173,  173,  136,  232,  136,
      136,  136,  136,  115,  138,  115,  139,  136,  136,  171,
      140,  181,  180,  181,  260,  259,  116,  116,  116,  116,
      116,  182,  119,  119,  119,  119,  119,  129,  235,  136,
      136,  196,  138,  196,  138,  199,  143,  196,  196,  255,
      202,  196,  129,  197,  197,  197,  197,  197,  254,  198,

      196,  145,  204,  145,  204,  152,  152,  152,  152,  152,
      253,  251,  205,  203,  146,  146,  146,  146,  146,  156,
      209,  156,  209,  158,  158,  158,  158,  158,  250,  166,
      210,  166,  157,  157,  157,  157,  157,  174,  170,  174,
      177,  172,  216,  172,  174,  177,  174,  200,  167,  218,
      226,  218,  226,  200,  173,  173,  173,  173,  173,  219,
      113,  214,  143,  114,  179,  217,  202,  181,  114,  181,
      144,  220,  196,  220,  196,  245,  144,  182,  196,  196,
      138,  241,  196,  214,  171,  221,  222,  180,  223,  203,
      276,  196,  197,  197,  197,  197,  197,  204,  233,  204,

      233,  209,  238,  209,  238,  170,  171,  205,  231,  216,
      138,  210,  234,  235,  256,  235,  239,  240,  218,  240,
      218,  242,  246,  242,  246,  220,  237,  220,  219,  247,
      236,  226,  217,  226,  138,  243,  244,  230,  244,  221,
      222,  248,  223,  248,  233,  257,  233,  257,  249,  238,
      129,  238,  258,  261,  242,  261,  242,  229,  234,  235,
      262,  235,  228,  239,  240,  264,  240,  264,  243,  244,
      227,  244,  265,  266,  246,  266,  246,  248,  129,  248,
      267,  247,  129,  269,  249,  269,  138,  257,  273,  257,
      261,  264,  261,  264,  258,  129,  225,  262,  265,  224,

      266,  271,  266,  269,  269,  269,  269,  267,  169,  213,
      212,  211,  208,  207,  206,  138,  194,  193,  192,  189,
      188,  271,  271,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  113,  113,  113,  113,
      129,  113,  113,  113,  113,  113,  113,  122,  187,  122,
      122,  136,  129,  186,  136,  136,  185,  184,  136,  136,
      136,  136,  138,  171,  169,  138,  138,  165,  164,  138,
      138,  138,  138,  143,  143,  143,  143,  163,  143,  143,

      143,  143,  143,  143,  147,  159,  147,  147,  154,  153,
      154,  154,  160,  151,  160,  160,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  170,  170,  170,
      170,  150,  170,  170,  170,  170,  170,  170,  175,  149,
      175,  175,  176,  176,  144,  142,  176,  176,  176,  176,
      176,  176,  176,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  116,  137,  135,  134,  133,  116,
      116,  183,  183,  132,  183,  183,  183,  183,  183,  183,
      183,  183,  195,  195,  131,  195,  195,  195,  195,  195,
      195,  195,  195,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  146,  128,  125,  124,  123,  146,
      146,  157,  121,  120,  112,  112,  157,  157,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  173,
      112,  112,  114,  112,  173,  173,  196,  196,  277,  196,
      196,  196,  196,  196,  196,  196,  196,  252,  277,  277,
      277,  277,  277,  277,  277,  277,  252,  270,  277,  277,
      277,  277,  277,  270,  270,  270,  270,   21,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277
    } ;

static const flex_int16_t yy_chk[1022] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    7,    8,   19,   20,
       19,   20,  276,    7,    8,    9,   46,    9,   32,    9,
        9,    9,   32,   46,    9,   23,   23,   23,   24,   24,
       24,   32,   61,    9,   33,   33,   33,   33,   33,   35,
       35,   44,  272,   44,   61,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   11,   11,   12,   12,   73,   73,
       11,  271,   12,   27,  113,   27,   74,   74,   68,  132,
       68,   82,   82,   11,  132,   12,   27,   27,   27,   27,
       27,   68,   68,   68,   68,   68,   11,  113,   12,   11,

      268,   12,   81,   81,   81,   81,   81,   87,   87,   87,
       88,   88,   88,   11,  254,   12,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   59,   90,   94,   90,   59,
       59,   59,  148,  148,   59,   59,   94,   59,   59,   90,
       90,   90,   90,   90,   59,  143,   59,   59,   59,   59,

       98,  250,   98,   59,   59,   59,   91,   91,   91,   91,
       91,  105,  243,  105,  110,  110,  110,  241,  143,   98,
      111,  111,  111,  155,  155,  155,   59,   59,   60,  102,
      239,  102,   60,   60,   60,  114,  170,   60,   60,  114,
       60,   60,  102,  102,  102,  102,  102,   60,  198,   60,
       60,   60,   60,  115,  198,  115,   60,   60,   60,  170,
       60,  116,  114,  116,  237,  236,  115,  115,  115,  115,
      115,  116,  119,  119,  119,  119,  119,  130,  234,   60,
       60,  137,  141,  137,  140,  141,  144,  137,  137,  230,
      144,  137,  130,  139,  139,  139,  139,  139,  228,  140,

      137,  145,  146,  145,  146,  152,  152,  152,  152,  152,
      227,  225,  146,  144,  145,  145,  145,  145,  145,  156,
      157,  156,  157,  158,  158,  158,  158,  158,  224,  166,
      157,  166,  156,  156,  156,  156,  156,  167,  171,  167,
      178,  172,  171,  172,  174,  179,  174,  201,  166,  173,
      188,  173,  188,  202,  172,  172,  172,  172,  172,  173,
      180,  215,  203,  178,  180,  171,  203,  181,  179,  181,
      201,  182,  195,  182,  195,  221,  202,  181,  195,  195,
      273,  213,  195,  216,  215,  182,  182,  180,  182,  203,
      273,  195,  197,  197,  197,  197,  197,  204,  205,  204,

      205,  209,  210,  209,  210,  217,  216,  204,  197,  217,
      232,  209,  205,  205,  232,  205,  210,  210,  218,  210,
      218,  219,  222,  219,  222,  220,  208,  220,  218,  222,
      206,  226,  217,  226,  199,  219,  219,  194,  219,  220,
      220,  223,  220,  223,  233,  235,  233,  235,  223,  238,
      193,  238,  235,  240,  242,  240,  242,  192,  233,  233,
      240,  233,  191,  238,  238,  244,  238,  244,  242,  242,
      190,  242,  244,  245,  246,  245,  246,  248,  189,  248,
      245,  246,  187,  252,  248,  252,  256,  257,  256,  257,
      261,  264,  261,  264,  257,  186,  185,  261,  264,  184,

      266,  252,  266,  269,  270,  269,  270,  266,  168,  165,
      163,  161,  151,  150,  149,  138,  135,  134,  133,  131,
      128,  269,  270,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  281,  281,  281,  281,
      127,  281,  281,  281,  281,  281,  281,  282,  126,  282,
      282,  283,  125,  124,  283,  283,  123,  121,  283,  283,
      283,  283,  284,  101,  100,  284,  284,   97,   96,  284,
      284,  284,  284,  285,  285,  285,  285,   95,  285,  285,

      285,  285,  285,  285,  286,   92,  286,  286,  287,   84,
      287,  287,  288,   79,  288,  288,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  290,  290,  290,
      290,   78,  290,  290,  290,  290,  290,  290,  291,   77,
      291,  291,  292,  292,   67,   64,  292,  292,  292,  292,
      292,  292,  292,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  294,   57,   51,   50,   49,  294,
      294,  295,  295,   48,  295,  295,  295,  295,  295,  295,
      295,  295,  296,  296,   47,  296,  296,  296,  296,  296,
      296,  296,  296,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  298,   45,   43,   42,   41,  298,
      298,  299,   39,   37,   34,   31,  299,  299,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  301,
       30,   29,   26,   25,  301,  301,  302,  302,   21,  302,
      302,  302,  302,  302,  302,  302,  302,  303,    0,    0,
        0,    0,    0,    0,    0,    0,  303,  304,    0,    0,
        0,    0,    0,  304,  304,  304,  304,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "v19.l"
#line 2 "v19.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_COMMENT_SIZE 2048
static char comment_buffer[MAX_COMMENT_SIZE];
static int comment_index = 0;

static char print_string[1024];
static char print_args[1024];
static int print_state_string_captured = 0;
static int at_count = 0;
static int arg_count = 0;
static int parentheses_count = 0;
static int varDeclPos = 0;
static char* symbolTable[256];
static int symbolCount = 0;
static int varDeclFlag = 0;
int while_parantheses_count = 0;
    char while_condition_buffer[1024];
    int while_condition_index = 0;

int isDeclared(const char* id) {
    int i;
    for(i = 0; i < symbolCount; i++){
        if(strcmp(symbolTable[i], id) == 0) return 1;
    }
    return 0;
}

void reset_print_buffers() {
    memset(print_string, 0, sizeof(print_string));
    memset(print_args, 0, sizeof(print_args));
    print_state_string_captured = 0;
    at_count = 0;
    arg_count = 0;
    parentheses_count = 0;
}

void reset_while_stats(){
        memset(while_condition_buffer, 0, sizeof(while_condition_buffer));
        while_parantheses_count = 0;
}

void count_at_symbols(const char* s) {
    int i;
    for (i = 0; s[i]; i++) {
        if (s[i] == '@') at_count++;
    }
}

void finalize_print_statement() {
    char temp[1204];
    snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    
    if (!print_state_string_captured) {
         printf("\t%-20s\t\t%s\t\n", temp, "Error: Invalid output statement");
         return;
    }
    if (at_count != arg_count) {
         char err_msg[256];
         snprintf(err_msg, sizeof(err_msg), "Error: Invalid output statement");
         printf("\t%-20s\t\t%s\t\n", temp, err_msg);
         return;
    }
    
    printf("\t%-20s\t\t%s\t\n", temp, "Valid output statement");
}

int validate_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (text[0] < 'a' || text[0] > 'z') return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9')) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_char_const(const char *text) {
    int len = strlen(text);
    if (text[0] == '\'' && text[len - 1] == '\'') {
        if (text[1] == '\\' && len == 4) return 1;
        else if (text[1] != '\\' && len == 3) return 1;
    }
    return 0;
}

int validate_decimal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '9') return 0;
    }
    return 1;
}

int validate_octal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '7') return 0;
    }
    return 1;
}

int validate_binary(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] != '0' && text[i] != '1') return 0;
    }
    return 1;
}

int validate_array_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (!((text[0] >= 'a' && text[0] <= 'z') || (text[0] >= 'A' && text[0] <= 'Z'))) return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_relational_expression(char * condition){
        char id1[256],op[3],id2[256];
        if(sscanf(condition,"%s %s %s",id1,op,id2)==3){
            if(!validate_identifier(id1) || !validate_identifier(id2)){
                return 0;
            }
            if(!(strcmp(op,"=")||strcmp(op,"<>")||strcmp(op,">")||strcmp(op,"<")||strcmp(op,">=")||strcmp(op,"<="))){
                return 0;
            }
            return 1;
        }
        else if(sscanf(condition,"%s",id1)==1){
            return validate_identifier(id1);
        }
        return 0;
}

void check_while_condition(){
    while_condition_buffer[while_condition_index] = '\0';
    if (validate_relational_expression(while_condition_buffer))
         printf("\t%-20s\t\t%s\t\n", while_condition_buffer, "valid condition in while loop");
    else
         printf("\t%-20s\t\t%s\t\n", while_condition_buffer, "Error: invalid condition in while loop");
}


int scan_arg_count=0;
int scan_paranthesis_count=0;
int scan_symbol_count=0;
int scan_fl=0;
char scan_string[1024];

void reset_scan_buffers(){
        scan_arg_count=0;
        scan_paranthesis_count=0;
        scan_symbol_count=0;
        scan_fl=0;
        scan_string[0]='\0';
}

void count_all_symbols(char*str)
{
    int idx=0;
    while(str[idx]!='\0')
    {
        if(str[idx]=='@')
        {
            scan_symbol_count++;
        }
        idx++;
    }

}

int validate_scan_placeholders(const char *s) {
    int atCount = 0, commaCount = 0;
    int len = strlen(s);
    int start = 0, end = len;

    if (len >= 2 && s[0] == '\"' && s[len - 1] == '\"') {
        start = 1;
        end = len - 1;
    }
    for (int i = start; i < end; i++) {
         if (s[i] == '\"')
             return 0;
         if (s[i] == '@')
             atCount++;
         else if (s[i] == ',')
             commaCount++;
    }
    if (atCount < 1 || commaCount != atCount - 1)
         return 0;
    return 1;
}

int statement_fl=0;
void reset_statement(){
    statement_fl=0;
}

int check_for_no_declaration(char*str){
    for(int i=0;i<symbolCount;i++)
    {
        if(strcmp(str,symbolTable[i])==0)
        {
            return 1;
        }
    
    }
    return 0;

}

int isKeyword(const char *word) {
    const char *keywords[] = {
        "begin", "end", "VarDecl", "int", "char", "if", "else", "while",
        "for", "print", "scan", "program", "inc", "dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(word, keywords[i]) == 0)
            return 1;
    }
    return 0;
}

#line 1027 "lex.yy.c"

#line 1029 "lex.yy.c"

#define INITIAL 0
#define VARDECL 1
#define NUMRELATIONS 2
#define COMMENT 3
#define PRINT 4
#define WHILE 5
#define CONDITION 6
#define FOR 7
#define SCAN 8
#define STRING 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 277 "v19.l"


#line 1258 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 278 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 968 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 279 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 283 "v19.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 285 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
    varDeclFlag = 1;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 290 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "separator");
    if (varDeclFlag) {
         BEGIN(VARDECL);
         varDeclFlag = 0;
    }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 298 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 302 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
    BEGIN(INITIAL);
}
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 308 "v19.l"
{ 
         varDeclPos = 0;
         printf("\t%-20s\t\t%s\t\n", yytext, "separator");
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 312 "v19.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "separator");
         varDeclPos = 0;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 316 "v19.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "separator");
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 319 "v19.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "separator");
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 322 "v19.l"
{ 
         printf("\t%-20s\t\t%s\t\n", yytext, "comment");
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 325 "v19.l"
{
         char arrName[256], sizeStr[64];
         if (sscanf(yytext, "%[^[][%[0-9]]", arrName, sizeStr) == 2) {
             if (varDeclPos == 0) {
                 if (isKeyword(arrName)) {
                     printf("\t%-20s\t\t%s\t\n", yytext, "Error: Keyword is used as an identifier");
                 } else if (validate_identifier(arrName)) {
                     int size = atoi(sizeStr);
                     if (size > 0) {
                         printf("\t%-20s\t\t%s\t\n", yytext, "array declaration");
                         if (!isDeclared(arrName)) {
                             symbolTable[symbolCount++] = strdup(arrName);
                         }
                     } else {
                         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid array size");
                     }
                 } else {
                     printf("\t%-20s\t\t%s\t\n", yytext, "error: invalid identifier");
                 }
             } else {  
                 printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
             }
             varDeclPos++;
         } else {
             printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid array declaration");
         }
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 352 "v19.l"
{
    if (varDeclPos == 0) { 
        if (isKeyword(yytext)) {
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: Keyword is used as an identifier");
        } else if (validate_identifier(yytext)) {
            if (!isDeclared(yytext)) {
                printf("\t%-20s\t\t%s\t\n", yytext, "identifier");
                symbolTable[symbolCount++] = strdup(yytext);
            } else {
                printf("\t%-20s\t\t%s\t\n", yytext, "Error: identifier already declared");
            }
        } else {
            printf("\t%-20s\t\t%s\t\n", yytext, "error: invalid identifier");
        }
    } else if (varDeclPos == 1) {  
        if (strcmp(yytext, "int") == 0 || strcmp(yytext, "char") == 0) {
            printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
        } else {
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid datatype");
        }
    } else {
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unexpected token in VarDecl");
    }
    varDeclPos++;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 377 "v19.l"
{
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid token in VarDecl");
    }
	YY_BREAK

case 15:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 382 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", "for", "keyword");
    BEGIN(FOR);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 387 "v19.l"
{
    yyless(0);
    BEGIN(WHILE);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 392 "v19.l"
{}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 394 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 398 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 402 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 406 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
    BEGIN(INITIAL); 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 411 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "identifier");
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 415 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "assignment operator");
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 419 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 423 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 427 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "arithmetic operator");
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 431 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "token");
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 435 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 439 "v19.l"
{
    reset_print_buffers();
    BEGIN(PRINT);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 444 "v19.l"
{
    reset_scan_buffers();
    BEGIN(SCAN);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 449 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
    BEGIN(WHILE);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 454 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 458 "v19.l"
{
    if (validate_identifier(yytext)) {
        if (isDeclared(yytext))
            printf("\t%-20s\t\t%s\t\n", yytext, "identifier");
        else 
            printf("\t%-20s\t\t%s\t\n", yytext, "Error: undefined identifier");
    }
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 467 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "comment");
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 471 "v19.l"
{
    BEGIN(COMMENT);
    comment_index = 0;
    comment_buffer[0] = '\0';
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 477 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", comment_buffer, "comment");
    BEGIN(INITIAL);
}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 482 "v19.l"
{
    if (comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = '\n';
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 489 "v19.l"
{
    if (comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = yytext[0];
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 497 "v19.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    int value_len = (int)(strchr(yytext, ',') - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_binary(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 510 "v19.l"
{
    char tmp[128];
    char *start = yytext + 1; 
    while (*start == ' ' || *start == '\t') 
        start++;
    char *comma_ptr = strchr(start, ','); 
    int value_len = (int)(comma_ptr - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_octal(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 525 "v19.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') 
        start++;
    char *comma_ptr = strchr(start, ',');  
    int value_len = (int)(comma_ptr - start);
    strncpy(tmp, start, value_len);
    tmp[value_len] = '\0';
    if (validate_decimal(tmp))
         printf("\t%-20s\t\t%s\t\n", yytext, "Integer constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 540 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid integer constant");
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 544 "v19.l"
{
    if (validate_char_const(yytext))
         printf("\t%-20s\t\t%s\t\n", yytext, "character constant");
    else 
         printf("\t%-20s\t\t%s\t\n", yytext, "Error: invalid character constant");
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 551 "v19.l"
{ 
    if (parentheses_count > 1) {
         printf("\t%-20s\t\t%s\t\n", "(", "Error: parenthesis count exceeds 1");
    }
    parentheses_count++;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 558 "v19.l"
{ BEGIN(STRING); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 560 "v19.l"
{ 
    strncat(print_string, yytext, sizeof(print_string)-strlen(print_string)-1);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 564 "v19.l"
{
     print_state_string_captured = 1;
     count_at_symbols(print_string);
     BEGIN(PRINT);
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 570 "v19.l"
{ 
    char temp[1204];
    snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    printf("\t%-20s\t\t%s\t\n", temp, "Error: Invalid output statement");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 578 "v19.l"
{ /* ignore or mark as separator if required */ }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 580 "v19.l"
{
    arg_count++;
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 584 "v19.l"
{
    arg_count++;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 588 "v19.l"
{
    if (!isDeclared(yytext))
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: variable not declared");
    else
        printf("\t%-20s\t\t%s\t\n", yytext, "identifier");
    arg_count++;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 596 "v19.l"
{
    if (parentheses_count > 1)
        printf("\t%-20s\t\t%s\t\n", ")", "Error: parenthesis count exceeds 1");
    if (parentheses_count > 0)
        parentheses_count--;
    else
        printf("\t%-20s\t\t%s\t\n", ")", "Error: unmatched closing parenthesis");
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 605 "v19.l"
{
    if (parentheses_count != 0)
        printf("\t%-20s\t\t%s\t\n", ";", "Error: parentheses not closed");
    else
        finalize_print_statement();
    BEGIN(INITIAL);
}
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 613 "v19.l"
{ 
    char temp[1204];
    snprintf(temp, sizeof(temp), "print(\"%s\");", print_string);
    if (parentheses_count != 0)
         printf("\t%-20s\t\t%s\t\n", temp, "missing closing parenthesis and semicolon");
    else
         printf("\t%-20s\t\t%s\t\n", temp, "missing semicolon");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 624 "v19.l"
{scan_paranthesis_count++;}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 625 "v19.l"
{ strncpy(scan_string,yytext,yyleng);
                    count_all_symbols(scan_string);
                     }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 628 "v19.l"
{ scan_arg_count++;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 630 "v19.l"
{ scan_arg_count++; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 631 "v19.l"
{ scan_arg_count++;
                        if(!validate_identifier(yytext))scan_fl=1;
                        else scan_fl=(check_for_no_declaration(yytext)==0)?1:scan_fl; 
                        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 635 "v19.l"
{scan_paranthesis_count--;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 636 "v19.l"
{
    char temp[1204];
    snprintf(temp, sizeof(temp), "scan(%s, num1, num2);", scan_string);
    if (!validate_scan_placeholders(scan_string))
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else if (scan_paranthesis_count != 0)
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else if (scan_arg_count != scan_symbol_count)
         printf("\t%-20s\t\t%s\t\n", temp, "Error: invalid input statement");
    else
         printf("\t%-20s\t\t%s\t\n", temp, "Valid input statement");
    BEGIN(INITIAL);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 649 "v19.l"
{}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 650 "v19.l"
{
            printf("Error: invalid input statement\n"); 
            BEGIN(INITIAL); 
        }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 655 "v19.l"
{
    BEGIN(INITIAL);
}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 659 "v19.l"
{ /* ignore whitespace in while */ }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 661 "v19.l"
{
    reset_while_stats();
    printf("\t%-20s\t\t%s\t\n", "(", "while opening brace");
    while_parantheses_count++;
    BEGIN(CONDITION);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 668 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "identifier in while condition");
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 672 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "relational operator in while condition");
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 676 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "constant in while condition");
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 680 "v19.l"
{
    while_parantheses_count--;
    if(while_parantheses_count != 0) {
        printf("\t%-20s\t\t%s\t\n", ")", "Error: missing matching parentheses");
        while_parantheses_count = 0;
    }
    printf("\t%-20s\t\t%s\t\n", ")", "while closing brace");
    BEGIN(WHILE);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 690 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
    while_parantheses_count++;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 695 "v19.l"
{
    while_parantheses_count--;
    if(while_parantheses_count)
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unmatched begin");
    else
        printf("\t%-20s\t\t%s\t\n", yytext, "keyword");
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 703 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "separator");
    BEGIN(INITIAL);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 708 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "separator");
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 712 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "arithmetic operator");
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 716 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "relational operator");
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 720 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "assignment operator");
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 724 "v19.l"
{
    printf("\t%-20s\t\t%s\t\n", yytext, "separator");
}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 728 "v19.l"
{}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 730 "v19.l"
{
    if(YYSTATE == PRINT)
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unexpected token");
    else
        printf("\t%-20s\t\t%s\t\n", yytext, "Error: unknown token");
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 737 "v19.l"
ECHO;
	YY_BREAK
#line 2049 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(VARDECL):
case YY_STATE_EOF(NUMRELATIONS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(PRINT):
case YY_STATE_EOF(WHILE):
case YY_STATE_EOF(CONDITION):
case YY_STATE_EOF(FOR):
case YY_STATE_EOF(SCAN):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 278 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 278 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 277);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 737 "v19.l"


int main(int argc, char **argv) {
    printf("\t%-20s\t\t%s\t\n", "LEXEMME", "TOKEN");
    yylex();
    return 0;
}

int yywrap(){
    return 1;
}
