
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[279] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       48,   48,    0,    0,    0,    0,    0,    0,   65,   63,
       62,   62,   58,   63,   61,   61,   58,   58,   58,   58,
       34,   61,   59,   59,   59,   57,   63,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   64,   64,
        5,   64,   64,   64,   64,   30,   29,   30,   47,   37,
       64,   36,   45,   41,   46,   44,   48,   49,   56,   64,
       64,   64,   64,   52,   51,   51,   51,   50,   19,    9,
        9,   18,   19,   17,   19,   14,   14,   14,   14,   14,
       38,   40,   39,   62,   60,    0,    0,    0,    0,   27,

       26,   34,   59,    0,   25,   25,   25,   25,   25,   25,
       25,   20,   25,   25,   25,   25,   25,    0,    6,    0,
        5,    0,    0,    0,    4,    0,   28,    0,    0,    0,
        0,   44,   48,    0,    0,    0,   53,   52,   51,   50,
        9,    0,    0,   17,   15,   14,   14,   13,   14,   10,
       14,   38,   35,    0,   35,    0,    0,    0,   26,    0,
       25,   25,   25,   20,   25,   25,   25,   25,   25,    0,
        0,    0,    0,    4,    0,   43,    0,   43,    0,    0,
        0,    0,   55,    0,    0,    0,   12,   11,   14,    0,
        0,    0,    0,    0,   25,    0,   25,   25,   22,   25,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,    0,    0,   31,    0,   32,
        0,   20,    0,   21,   25,   23,    0,    0,    0,    0,
        0,    0,   42,   54,   24,    0,   16,    8,    0,   33,
        0,    0,    0,    0,    0,   25,    0,    0,    0,    0,
       20,    0,    7,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    3,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    0,    2,    2,    0,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        8,    9,   10,   11,   12,    1,   13,   14,   15,   16,
       17,   17,   17,   17,   17,   18,   17,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   26,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   27,   25,   25,   25,   25,
       28,   29,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   41,   42,   43,   44,
       45,   46,   41,   47,   48,   49,   41,   41,   50,   41,
       41,   41,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    3,    4,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    6,    6,    6,    6,    6,    7,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        6,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1
    } ;

static const flex_int16_t yy_base[298] =
    {   0,
        0,    0,   51,   53,    0,    0,   54,   56,   87,    0,
       66,   68,  137,    0,  189,    0,   58,   73,  803,  804,
       76,   78,  780,  772,   94,  804,  778,  777,  776,  233,
      233,  775,   60,  804,  774,  804,  763,    0,  758,  754,
      756,   30,  746,   48,  758,  742,  754,  748,  783,  250,
      804,  256,  100,  240,  804,  804,  804,  772,  804,  804,
      755,  252,  804,  804,  804,    0,  103,  804,  804,  747,
      738,  742,  777,  246,   92,  804,  757,    0,  804,  242,
      269,  804,  305,  259,  756,    0,  220,  733,  731,  736,
        0,  804,  804,  276,  804,  279,  306,  311,  322,  804,

        0,  300,  804,  727,    0,  735,  740,  737,  722,  734,
      721,    0,  296,  727,  301,  734,  725,  761,  804,  340,
      804,    0,    0,  347,  760,  397,  804,  281,  398,  400,
      408,    0,  329,  724,  726,  709,  804,  391,  804,    0,
      409,  419,  427,  432,  804,    0,  714,    0,  713,    0,
      704,    0,  804,  305,  422,  449,  428,  438,    0,  717,
      702,  694,  704,  715,  658,  657,  659,  650,  649,  455,
      457,    0,  459,  683,  461,  804,  459,  461,  465,  468,
      480,  632,  804,  625,  470,  484,    0,    0,  587,  490,
      614,  278,  485,  591,  582,  623,  575,  576,    0,  586,

      482,  486,  466,  512,  528,  509,  502,  606,  499,  575,
      582,  517,  603,  501,  580,  532,  539,  804,  546,  804,
      581,  611,   65,    0,  580,    0,  518,  510,  549,  534,
      521,  547,  804,  804,  804,  554,  804,    0,  555,  804,
      569,  559,   98,  401,  588,  553,  520,  563,  566,  536,
      804,  562,  804,  570,  572,  567,  491,  577,  582,  578,
      454,  585,  804,  586,  587,  395,  598,  588,  379,  600,
      602,  604,  302,  606,  804,   78,  804,  804,  630,  638,
      646,  654,  662,  665,  673,  681,  684,  687,  690,  698,
      706,  714,  722,  730,  737,  744,  752

    } ;

static const flex_int16_t yy_def[298] =
    {   0,
      278,    1,  279,  279,  280,  280,  281,  281,  280,    9,
      280,  280,  278,   13,  278,   15,  282,  282,  278,  278,
      278,  278,  278,  283,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  285,  285,
      278,  285,  285,  285,  278,  278,  278,  278,  278,  278,
      286,  278,  278,  278,  278,  287,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  288,  278,  278,
      278,  278,  278,  278,  278,  289,  289,  289,  289,  289,
      290,  278,  278,  278,  278,  283,  291,  278,  278,  278,

      292,  278,  278,  278,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  285,  278,  285,
      278,   52,   52,  278,  293,  285,  278,  286,  294,  278,
      278,  287,  278,  278,  278,  278,  278,  278,  278,  288,
      278,  278,  278,  278,  278,  289,  289,  289,  289,  289,
      289,  290,  278,  283,  283,  291,  278,  278,  292,  278,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  285,
      285,  124,  285,  293,  285,  278,  286,  286,  294,  278,
      278,  278,  278,  278,  278,  278,  289,  289,  289,  278,
      278,  278,  278,  278,  284,  295,  284,  284,  284,  284,

      285,  285,  285,  285,  285,  285,  278,  278,  278,  278,
      278,  278,  278,  278,  289,  278,  278,  278,  278,  278,
      278,  284,  296,  284,  284,  284,  285,  285,  285,  285,
      285,  278,  278,  278,  278,  278,  278,  289,  278,  278,
      278,  278,  278,  296,  278,  284,  285,  285,  285,  285,
      278,  278,  278,  285,  285,  285,  278,  285,  285,  285,
      278,  285,  278,  285,  285,  278,  297,  285,  278,  297,
      297,  285,  278,  285,  278,  278,  278,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278

    } ;

static const flex_int16_t yy_nxt[857] =
    {   0,
       20,   21,   22,   20,   23,   24,   25,   26,   27,   28,
       26,   29,   30,   31,   31,   31,   31,   31,   32,   26,
       33,   34,   35,   36,   20,   20,   37,   20,   20,   20,
       20,   38,   39,   40,   41,   42,   43,   38,   38,   44,
       38,   38,   45,   38,   38,   46,   38,   47,   38,   48,
       26,   26,   50,   51,   50,   51,   57,   52,   57,   52,
       92,   93,   58,   53,   58,   53,  243,   67,   67,   67,
       67,  109,   68,  110,   68,   92,   93,   94,   94,   94,
       94,  103,  103,  245,  112,   69,   54,   69,   54,   59,
       60,  113,   61,   62,   63,   98,  277,   64,   70,  243,

       70,   71,  119,   71,  133,  133,   65,   99,   99,   99,
       99,   99,  125,  139,  139,   72,  245,   72,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   55,   55,   55,
       55,   55,   55,   55,   73,   55,   55,   55,   55,   55,
       74,   74,   74,   74,   74,   55,   55,   75,   76,   77,
       55,   55,   55,   55,   55,   55,   55,   55,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   55,   55,   79,
       80,   81,   79,   82,   79,   83,   79,   82,   82,   79,

       82,   82,   84,   84,   84,   84,   84,   85,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       86,   86,   86,   87,   86,   86,   86,   86,   88,   86,
       86,   86,   86,   86,   86,   86,   86,   89,   90,   79,
       79,  100,  119,  141,  141,  101,  102,  102,  102,  102,
      102,  120,  121,  130,   95,  147,  122,  123,  119,  138,
      138,  138,  138,  138,  148,  131,  131,  131,  131,  131,
      141,  141,  144,  144,  144,  144,  144,   94,   94,  217,
      124,  124,  124,  126,  153,  218,  176,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,

      124,  124,  124,  124,  124,  124,  142,   97,   96,  129,
      153,  155,   98,  102,  102,  102,  102,  102,  143,  143,
      143,  143,  143,  157,   99,   99,   99,   99,   99,  112,
      133,  133,  158,   97,  156,   99,   99,   99,   99,   99,
      166,  120,  121,  276,  112,  167,  122,  118,  170,  119,
      118,  118,  118,  118,  118,  118,  118,  171,  118,  118,
      172,  172,  172,  172,  172,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  173,  118,  118,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  118,  118,  119,

      128,  130,  243,  178,  138,  138,  138,  138,  138,  180,
      141,  141,  273,  131,  131,  131,  131,  131,  181,  245,
      142,  131,  131,  131,  131,  131,  179,  153,  185,  157,
      269,  175,  143,  143,  143,  143,  143,  186,  158,  190,
      143,  143,  143,  143,  143,  144,  144,  144,  144,  144,
       97,   96,  191,  192,  155,  193,  170,  119,  201,  119,
      204,  119,  206,  119,  176,  171,  176,  128,  119,  180,
      178,  185,  205,  205,  205,  205,  205,  156,  181,  266,
      186,  207,  173,  201,  119,  212,  219,  129,  119,  129,
      202,  190,  220,  179,  208,  209,  203,  209,  213,  214,

      232,  214,  236,  207,  191,  192,  233,  193,  237,  228,
      206,  119,  119,  204,  119,  202,  208,  209,  212,  209,
      119,  203,  119,  119,  227,  205,  205,  205,  205,  205,
      119,  213,  214,  239,  214,  231,  119,  261,  119,  240,
      217,  205,  205,  205,  205,  205,  218,  219,  232,  247,
      249,  119,  250,  220,  233,  236,  239,  229,  248,  171,
      242,  237,  240,  229,  254,  119,  248,  249,  119,  119,
      255,  254,  119,  258,  119,  230,  171,  255,  258,  119,
      119,  230,  256,  262,  263,  252,  262,  263,  119,  119,
      119,  259,  260,  257,  264,  112,  259,  264,  267,  271,

      263,  271,  263,  271,  263,  274,  275,  274,  275,  253,
      251,  246,  242,  265,  241,  238,  214,  235,  234,  209,
      268,  226,  225,  224,  196,  222,  221,  216,  215,  272,
       49,   49,   49,   49,   49,   49,   49,   49,   55,   55,
       55,   55,   55,   55,   55,   55,   56,   56,   56,   56,
       56,   56,   56,   56,   91,   91,   91,   91,   91,   91,
       91,   91,   96,   96,   96,   96,  211,   96,   96,   96,
      105,  210,  105,  118,  118,  118,  118,  118,  118,  118,
      118,  128,  128,  128,  128,  119,  128,  128,  128,  132,
      200,  132,  140,  199,  140,  146,  198,  146,  152,  152,

      197,  112,  152,  152,  152,  152,  154,  154,  154,  154,
      154,  154,  154,  154,  159,  159,  196,  159,  159,  159,
      159,  159,  174,  174,  174,  174,  174,  174,  174,  174,
      177,  177,  177,  177,  177,  177,  177,  177,  223,  112,
      112,  195,  194,  189,  223,  244,  188,  187,  184,  244,
      244,  244,  270,  270,  270,  270,  270,  270,  270,  270,
      183,  182,  119,  119,  169,  168,  165,  164,  112,  163,
      112,  162,  161,  160,  151,  150,  149,  145,  139,  137,
      136,  135,  134,  129,  127,  119,  117,  116,  115,  114,
      111,  108,  107,  106,  104,  103,   95,   95,   95,   95,

       97,   95,  278,   19,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278
    } ;

static const flex_int16_t yy_chk[857] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    7,    3,    8,    4,
       17,   17,    7,    3,    8,    4,  223,   11,   11,   12,
       12,   42,   11,   42,   12,   18,   18,   21,   21,   22,
       22,   33,   33,  223,   44,   11,    3,   12,    4,    9,
        9,   44,    9,    9,    9,   25,  276,    9,   11,  243,

       12,   11,   53,   12,   67,   67,    9,   25,   25,   25,
       25,   25,   53,   75,   75,   11,  243,   12,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   30,   54,   80,   80,   30,   31,   31,   31,   31,
       31,   50,   50,   62,   30,   87,   50,   52,   52,   74,
       74,   74,   74,   74,   87,   62,   62,   62,   62,   62,
       81,   81,   84,   84,   84,   84,   84,   94,   94,  192,
       52,   52,   52,   54,   96,  192,  128,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   83,   96,   97,  128,
      154,   97,   98,  102,  102,  102,  102,  102,   83,   83,
       83,   83,   83,   99,   98,   98,   98,   98,   98,  113,
      133,  133,   99,  154,   97,   99,   99,   99,   99,   99,
      115,  120,  120,  273,  113,  115,  120,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  126,

      129,  130,  244,  129,  138,  138,  138,  138,  138,  131,
      141,  141,  269,  130,  130,  130,  130,  130,  131,  244,
      142,  131,  131,  131,  131,  131,  129,  155,  143,  157,
      266,  126,  142,  142,  142,  142,  142,  143,  157,  158,
      143,  143,  143,  143,  143,  144,  144,  144,  144,  144,
      155,  156,  158,  158,  156,  158,  170,  170,  171,  171,
      173,  173,  175,  175,  177,  170,  178,  179,  203,  180,
      179,  185,  173,  173,  173,  173,  173,  156,  180,  261,
      185,  181,  170,  201,  201,  186,  193,  177,  202,  178,
      171,  190,  193,  179,  181,  181,  171,  181,  186,  186,

      209,  186,  214,  207,  190,  190,  209,  190,  214,  203,
      206,  206,  228,  204,  204,  201,  207,  207,  212,  207,
      227,  201,  247,  231,  202,  204,  204,  204,  204,  204,
      205,  212,  212,  216,  212,  206,  230,  257,  250,  216,
      217,  205,  205,  205,  205,  205,  217,  219,  232,  227,
      229,  229,  231,  219,  232,  236,  239,  205,  228,  229,
      242,  236,  239,  230,  248,  248,  247,  249,  249,  256,
      248,  254,  254,  255,  255,  205,  249,  254,  258,  258,
      260,  230,  250,  259,  259,  242,  262,  262,  264,  265,
      268,  255,  256,  252,  259,  246,  258,  262,  264,  267,

      267,  270,  270,  271,  271,  272,  272,  274,  274,  245,
      241,  225,  222,  260,  221,  215,  213,  211,  210,  208,
      265,  200,  198,  197,  196,  195,  194,  191,  189,  268,
      279,  279,  279,  279,  279,  279,  279,  279,  280,  280,
      280,  280,  280,  280,  280,  280,  281,  281,  281,  281,
      281,  281,  281,  281,  282,  282,  282,  282,  282,  282,
      282,  282,  283,  283,  283,  283,  184,  283,  283,  283,
      284,  182,  284,  285,  285,  285,  285,  285,  285,  285,
      285,  286,  286,  286,  286,  174,  286,  286,  286,  287,
      169,  287,  288,  168,  288,  289,  167,  289,  290,  290,

      166,  165,  290,  290,  290,  290,  291,  291,  291,  291,
      291,  291,  291,  291,  292,  292,  164,  292,  292,  292,
      292,  292,  293,  293,  293,  293,  293,  293,  293,  293,
      294,  294,  294,  294,  294,  294,  294,  294,  295,  163,
      162,  161,  160,  151,  295,  296,  149,  147,  136,  296,
      296,  296,  297,  297,  297,  297,  297,  297,  297,  297,
      135,  134,  125,  118,  117,  116,  114,  111,  110,  109,
      108,  107,  106,  104,   90,   89,   88,   85,   77,   73,
       72,   71,   70,   61,   58,   49,   48,   47,   46,   45,
       43,   41,   40,   39,   37,   35,   32,   29,   28,   27,

       24,   23,   19,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "v10.l"
#line 2 "v10.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_COMMENT_SIZE 2048
static char comment_buffer[MAX_COMMENT_SIZE];
static int comment_index = 0;

static char print_string[1024];
static char print_args[1024];
static int print_state_string_captured = 0;
static int at_count = 0;
static int arg_count = 0;
static int parentheses_count = 0;

static char* symbolTable[256];
static int symbolCount = 0;

int while_parantheses_count = 0;
    char while_condition_buffer[1024];
    int while_condition_index = 0;

int isDeclared(const char* id) {
    int i;
    for(i = 0; i < symbolCount; i++){
        if(strcmp(symbolTable[i], id) == 0) return 1;
    }
    return 0;
}

void reset_print_buffers() {
    memset(print_string, 0, sizeof(print_string));
    memset(print_args, 0, sizeof(print_args));
    print_state_string_captured = 0;
    at_count = 0;
    arg_count = 0;
    parentheses_count = 0;
}

void reset_while_stats(){
        memset(while_condition_buffer, 0, sizeof(while_condition_buffer));
        while_parantheses_count = 0;
}

void count_at_symbols(const char* s) {
    int i;
    for (i = 0; s[i]; i++) {
        if (s[i] == '@') at_count++;
    }
}

void finalize_print_statement() {
    if (!print_state_string_captured) {
        printf("INVALID PRINT STATEMENT: Missing double quotes.\n");
        return;
    }
    if (at_count != arg_count) {
        printf("INVALID PRINT STATEMENT: @ count (%d) != argument count (%d).\n", at_count, arg_count);
        return;
    }
    printf("VALID PRINT STATEMENT: %s\n", print_string);
}

int validate_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (text[0] < 'a' || text[0] > 'z') return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9')) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_char_const(const char *text) {
    int len = strlen(text);
    if (text[0] == '\'' && text[len - 1] == '\'') {
        if (text[1] == '\\' && len == 4) return 1;
        else if (text[1] != '\\' && len == 3) return 1;
    }
    return 0;
}

int validate_decimal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '9') return 0;
    }
    return 1;
}

int validate_octal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '7') return 0;
    }
    return 1;
}

int validate_binary(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] != '0' && text[i] != '1') return 0;
    }
    return 1;
}

int validate_array_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (!((text[0] >= 'a' && text[0] <= 'z') || (text[0] >= 'A' && text[0] <= 'Z'))) return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_relational_expression(char * condition){
        char id1[256],op[3],id2[256];
        if(sscanf(condition,"%s %s %s",id1,op,id2)==3){
            if(!validate_identifier(id1) || !validate_identifier(id2)){
                return 0;
            }
            if(!(strcmp(op,"=")||strcmp(op,"<>")||strcmp(op,">")||strcmp(op,"<")||strcmp(op,">=")||strcmp(op,"<="))){
                return 0;
            }
            return 1;
        }
        else if(sscanf(condition,"%s",id1)==1){
            return validate_identifier(id1);
        }
        return 0;
}

void check_while_condition(){
        while_condition_buffer[while_condition_index] = '\0';
        if(validate_relational_expression(while_condition_buffer)){
            printf("VALID CONDITION IN WHILE LOOP\n");
        }
        else{
            printf("INVALID CONDITION IN WHILE LOOP\n");
        }
}
#line 900 "lex.yy.c"

#line 902 "lex.yy.c"

#define INITIAL 0
#define VARDECL 1
#define NUMRELATIONS 2
#define COMMENT 3
#define PRINT 4
#define WHILE 5
#define CONDITION 6
#define FOR 7
#define STRING 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 186 "v10.l"


#line 1130 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 804 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 188 "v10.l"
{ BEGIN(VARDECL); printf("BEGIN VARIABLE DECLARATION\n"); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 190 "v10.l"
{
    BEGIN(INITIAL);
    printf("END VARIABLE DECLARATION\n");
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 195 "v10.l"
{
    char lineCopy[1024];
    strncpy(lineCopy, yytext, 1023);
    lineCopy[1023] = '\0';
    {
        char *commentStart = strstr(lineCopy, "//");
        if(commentStart) {
            printf("COMMENT: %s\n", commentStart);
            *commentStart = '\0';
        }
    }
    if (strchr(lineCopy, '[')) {
        char id[64], typ[16];
        int size;
        if (sscanf(lineCopy, " ( %63[^[]%*c%d%*c , %15[^)] ) ;", id, &size, typ) == 3) {
            char *nl = strpbrk(typ, " \t");
            if (nl) *nl = '\0';
            if (size > 0 && validate_array_identifier(id)) {
                printf("VALID ARRAY DECLARATION: (%s[%d], %s)\n", id, size, typ);
                symbolTable[symbolCount++] = strdup(id);
            }
            else
                printf("INVALID ARRAY DECLARATION: %s\n", yytext);
        } else {
            printf("INVALID ARRAY DECLARATION: %s\n", yytext);
        }
    } else {
        char id[64], typ[16];
        if (sscanf(lineCopy, " ( %63[^,] , %15[^)] ) ;", id, typ) == 2) {
            char *nl = strpbrk(typ, " \t");
            if(nl) *nl = '\0';
            if (validate_identifier(id)) {
                printf("VALID VARIABLE DECLARATION: (%s, %s)\n", id, typ);
                symbolTable[symbolCount++] = strdup(id);
            }
            else
                printf("INVALID VARIABLE DECLARATION: %s\n", yytext);
        } else {
            printf("INVALID VARIABLE DECLARATION: %s\n", yytext);
        }
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 238 "v10.l"
{
    printf("COMMENT: %s\n", yytext);
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 242 "v10.l"
{
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 245 "v10.l"
{
    printf("INVALID VARIABLE DECLARATION: %s", yytext);
}
	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "v10.l"
{
    printf("KEYWORD: for\n");
    BEGIN(FOR);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 254 "v10.l"
{
    yyless(0);
    BEGIN(WHILE);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 259 "v10.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 261 "v10.l"
{
    printf("FOR-DO KEYWORD: to\n");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 265 "v10.l"
{
    printf("FOR-DO KEYWORD: inc\n");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 269 "v10.l"
{
    printf("FOR-DO KEYWORD: dec\n");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 273 "v10.l"
{
    printf("FOR-DO KEYWORD: do\n");
    BEGIN(INITIAL); 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 278 "v10.l"
{
    printf("FOR-DO INDEX VARIABLE: %s\n", yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 282 "v10.l"
{
    printf("ASSIGNMENT OPERATOR (FOR-DO): %s\n", yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 286 "v10.l"
{
    printf("FOR-DO CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 290 "v10.l"
{
    printf("FOR-DO INTEGER CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 294 "v10.l"
{
    printf("FOR-DO ARITHMETIC OPERATOR: %s\n", yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 298 "v10.l"
{
    printf("FOR-DO TOKEN: %s\n", yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 302 "v10.l"
{
    printf("KEYWORD: %s\n", yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 306 "v10.l"
{
    printf("KEYWORD: %s\n", yytext);
    reset_print_buffers();
    BEGIN(PRINT);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 312 "v10.l"
{
    printf("KEYWORD: %s\n", yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 316 "v10.l"
{
    printf("KEYWORD: %s\n",yytext);
    BEGIN(WHILE);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 321 "v10.l"
{
    printf("KEYWORD: %s\n", yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 325 "v10.l"
{
    if (validate_identifier(yytext)) {
        if (isDeclared(yytext)) printf("IDENTIFIER: %s\n", yytext);
        else printf("UNDEFINED IDENTIFIER: %s\n", yytext);
    }
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 332 "v10.l"
{
    printf("COMMENT: %s\n", yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 336 "v10.l"
{
    BEGIN(COMMENT);
    comment_index = 0;
    comment_buffer[0] = '\0';
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 342 "v10.l"
{
    printf("COMMENT (multiline): /*%s*/\n", comment_buffer);
    BEGIN(INITIAL);
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 347 "v10.l"
{
    if(comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = '\n';
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 354 "v10.l"
{
    if(comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = yytext[0];
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 361 "v10.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_binary(tmp)) printf("BINARY INTEGER CONSTANT: (%s, 2)\n", tmp);
    else printf("INVALID BINARY CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 374 "v10.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_octal(tmp))
        printf("OCTAL INTEGER CONSTANT: (%s, 8)\n", tmp);
    else
        printf("INVALID OCTAL CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 389 "v10.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_decimal(tmp)) printf("DECIMAL INTEGER CONSTANT: (%s, 10)\n", tmp);
    else printf("INVALID DECIMAL CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 402 "v10.l"
{
    printf("INVALID INTEGER CONSTANT: Missing base in %s\n", yytext);
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 406 "v10.l"
{
    if (validate_char_const(yytext)) printf("CHARACTER CONSTANT: %s\n", yytext);
    else printf("INVALID CHARACTER CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 411 "v10.l"
{ parentheses_count++; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 413 "v10.l"
{ BEGIN(STRING); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 415 "v10.l"
{ strncat(print_string, yytext, sizeof(print_string)-strlen(print_string)-1); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 417 "v10.l"
{ print_state_string_captured = 1; count_at_symbols(print_string); BEGIN(PRINT); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 419 "v10.l"
{ printf("INVALID PRINT STATEMENT: Missing closing double quotes.\n"); reset_print_buffers(); BEGIN(INITIAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 421 "v10.l"
{
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 424 "v10.l"
{
    arg_count++;
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 428 "v10.l"
{
    arg_count++;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 432 "v10.l"
{
    if (!isDeclared(yytext)) {
        printf("ERROR: Variable '%s' in print statement not declared.\n", yytext);
    }
    arg_count++;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 439 "v10.l"
{
    if (parentheses_count > 0) parentheses_count--;
    else printf("INVALID PRINT STATEMENT: Unmatched closing parenthesis.\n");
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 444 "v10.l"
{
    if (parentheses_count != 0) printf("INVALID PRINT STATEMENT: Parentheses not closed.\n");
    else finalize_print_statement();
    BEGIN(INITIAL);
}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 450 "v10.l"
{
    if (parentheses_count != 0) printf("INVALID PRINT STATEMENT: Missing closing parenthesis and semicolon.\n");
    else printf("INVALID PRINT STATEMENT: Missing semicolon.\n");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 457 "v10.l"
{
    //ignore whitespaces and blanks
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 461 "v10.l"
{
 reset_while_stats();
 printf("WHILE OPENING BRACE: %s\n",yytext);
 while_parantheses_count++;
 BEGIN(CONDITION);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 467 "v10.l"
{
    printf("IDENTIFIER IN WHILE CONDITION: %s\n", yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 470 "v10.l"
{
    printf("RELATIONAL OPERATOR IN WHILE CONDITION: %s\n", yytext);
    while_condition_buffer[while_condition_index++] = yytext[0];
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 474 "v10.l"
{
    printf("CONSTANT IN WHILE CONDITION: %s\n", yytext);
    while_condition_buffer[while_condition_index++] = yytext[0];
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 479 "v10.l"
{
    while_parantheses_count--;
    if(while_parantheses_count!=0){
        printf("INVALID WHILE LOOP STATEMENT: MISSING MATCHING PARANTHESES\n");
        while_parantheses_count = 0;
    }
    printf("WHILE CLOSING BRACE: %s\n",yytext);
    BEGIN(WHILE);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 490 "v10.l"
{
    printf("KEYWORD: %s\n", yytext);
    while_parantheses_count++;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 495 "v10.l"
{
    while_parantheses_count--;
    if(while_parantheses_count){
        printf("ERROR: you have entered end without a matching begin\n");
    }
    else{
        printf("KEYWORD: %s\n",yytext);
    }
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 504 "v10.l"
{
    printf("SEPERATOR: %s\n",yytext);
    BEGIN(INITIAL);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 509 "v10.l"
{
    printf("SEPARATOR: %s\n", yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 513 "v10.l"
{
    printf("ARITHMETIC OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 517 "v10.l"
{
    printf("RELATIONAL OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 521 "v10.l"
{
    printf("ASSIGNMENT OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 525 "v10.l"
{
    printf("SEPARATOR: %s\n", yytext);
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 529 "v10.l"
{
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 532 "v10.l"
{
    if (YYSTATE == PRINT) printf("INVALID PRINT STATEMENT: Unexpected token '%s'\n", yytext);
    else printf("UNKNOWN TOKEN: %s\n", yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 537 "v10.l"
ECHO;
	YY_BREAK
#line 1749 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(VARDECL):
case YY_STATE_EOF(NUMRELATIONS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(PRINT):
case YY_STATE_EOF(WHILE):
case YY_STATE_EOF(CONDITION):
case YY_STATE_EOF(FOR):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 278);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 537 "v10.l"


int main(int argc, char **argv) {
    yylex();
    return 0;
}

