
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[274] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   57,   55,   54,   54,
       50,   55,   53,   53,   50,   50,   50,   50,   32,   53,
       51,   51,   51,   49,   55,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   56,   56,    5,   56,
       56,   56,   56,   28,   27,   28,   42,   56,   56,   34,
       40,   36,   41,   39,   43,   44,   56,   56,   56,   45,
       45,   18,    8,    8,   17,   18,   16,   18,   13,   13,
       13,   13,   54,   52,    0,    0,    0,    0,   25,   24,
       32,   51,    0,   23,   23,   23,   23,   23,   23,   23,

       19,   23,   23,   23,   23,   23,    0,    6,    0,    5,
        0,    0,    0,    4,    0,   26,    0,   35,    0,    0,
        0,    0,   39,    0,    0,   46,   45,   45,   45,   45,
       45,   45,    8,    0,    0,   16,   14,   13,   13,   12,
       13,    9,   33,    0,   33,    0,    0,    0,   24,    0,
       23,   23,   23,   19,   23,   23,   23,   23,   23,    0,
        0,    0,    0,    4,    0,   38,    0,   38,    0,    0,
        0,    0,    0,   45,   45,   45,   45,    0,    0,   11,
       10,    0,    0,    0,    0,    0,   23,    0,   23,   23,
       21,   23,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   48,   45,   45,   45,   45,   45,   45,    0,
        0,    0,    0,    0,   29,    0,   30,    0,   19,    0,
       20,   23,   22,    0,    0,    0,    0,    0,    0,   37,
       47,    0,   15,    0,   31,    0,    0,    0,    0,    0,
       23,    0,    0,    0,    0,   19,    0,    7,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    3,    0,    0,
        0,    0,    0,    0,    0,    0,    2,    0,    2,    2,
        0,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    6,    7,
        8,    9,   10,   11,   12,    1,   13,   14,   15,   16,
       17,   17,   17,   17,   17,   18,   17,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   26,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   27,   25,   25,   25,   25,
       28,   29,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   41,   42,   43,   44,
       45,   46,   41,   47,   48,   49,   41,   41,   50,   41,
       41,   41,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    6,    1,
        7,    8,    9,    1,    1,    1,    1,    1,    1,    1,
       10,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        1,    1
    } ;

static const flex_int16_t yy_base[296] =
    {   0,
        0,    0,   51,   53,    0,    0,   54,   56,   87,    0,
       64,   66,  130,    0,  180,    0,  861,  862,   59,   72,
      838,  830,   66,  862,  836,  835,  834,   63,   94,  833,
       55,  862,  832,  862,  821,    0,  816,  812,  814,   44,
      804,   59,  816,  800,  812,  806,  841,  111,  862,  231,
      102,   98,  862,  862,  862,  817,  862,  825,  799,  137,
      862,  862,  862,    0,  862,  862,  789,  780,  818,  214,
      268,  862,  114,  138,  862,  142,  131,  798,    0,   34,
      775,  773,  236,  862,  230,  284,  286,  294,  862,    0,
      226,  862,  770,    0,  778,  783,  780,  763,  775,  762,

        0,  211,  768,  206,  775,  764,  800,  862,  245,  862,
        0,    0,  316,  799,  258,  862,  797,  862,  286,  366,
      368,  376,    0,  762,  762,  862,  350,  385,  420,  356,
      391,  455,  247,  403,  411,  430,  862,    0,  760,    0,
      759,    0,  862,  368,  382,  403,  295,  438,    0,  735,
      705,  697,  707,  740,  695,  693,  697,  688,  688,  413,
      447,    0,  449,  725,  251,  862,  451,  453,  455,  296,
      473,  684,  703,  478,  700,  673,  483,  378,  500,    0,
        0,  504,  698,  373,  475,  648,  639,  680,  632,  625,
        0,  598,  483,  471,  501,  522,  543,  428,  512,  619,

      503,  588,  862,  583,  582,  581,  533,  580,  538,  560,
      613,  505,  527,  561,  862,  562,  862,  592,  605,  460,
        0,  476,    0,  509,  101,  531,  541,  540,  566,  862,
      862,  575,  862,  577,  862,  418,  563,  565,  578,  401,
      367,  252,  585,  592,  563,  862,  364,  862,  596,  598,
      506,  329,  603,  606,  579,  288,  609,  862,  589,  487,
      125,  292,  593,  109,  611,  614,  618,   64,  622,  862,
       73,  862,  862,  635,  646,  657,  668,  675,  686,  697,
      708,  715,  722,  729,  736,  747,  758,  769,  780,  787,
      794,  801,  811,  821,  832

    } ;

static const flex_int16_t yy_def[296] =
    {   0,
      273,    1,  274,  274,  275,  275,  276,  276,  275,    9,
      275,  275,  275,   13,  273,   15,  273,  273,  273,  273,
      273,  277,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  279,  279,  273,  279,
      279,  279,  273,  273,  273,  273,  273,  280,  281,  273,
      273,  273,  273,  282,  273,  273,  273,  273,  273,  283,
      284,  273,  273,  273,  273,  273,  273,  273,  285,  285,
      285,  285,  273,  273,  277,  286,  273,  273,  273,  287,
      273,  273,  273,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  279,  273,  279,  273,
       50,   50,  273,  288,  279,  273,  280,  273,  281,  289,
      273,  273,  282,  273,  273,  273,  283,  290,  290,  283,
      283,  284,  273,  273,  273,  273,  273,  285,  285,  285,
      285,  285,  273,  277,  277,  286,  273,  273,  287,  273,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  279,
      279,  113,  279,  288,  279,  273,  281,  281,  289,  273,
      273,  273,  273,  273,  129,  291,  292,  273,  273,  285,
      285,  273,  273,  273,  273,  273,  278,  293,  278,  278,
      278,  278,  279,  279,  279,  279,  279,  279,  273,  273,

      273,  273,  273,  273,  291,  291,  291,  291,  292,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  278,  294,
      278,  278,  278,  279,  279,  279,  279,  279,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  294,  273,
      278,  279,  279,  279,  279,  273,  273,  273,  279,  279,
      279,  273,  279,  279,  279,  273,  279,  273,  279,  279,
      273,  295,  279,  273,  295,  295,  279,  273,  279,  273,
      273,  273,    0,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273

    } ;

static const flex_int16_t yy_nxt[915] =
    {   0,
       18,   19,   20,   18,   21,   22,   23,   24,   25,   26,
       24,   27,   28,   29,   29,   29,   29,   29,   30,   24,
       31,   32,   33,   34,   18,   18,   35,   18,   18,   18,
       18,   36,   37,   38,   39,   40,   41,   36,   36,   42,
       36,   36,   43,   36,   36,   44,   36,   45,   36,   46,
       24,   24,   48,   49,   48,   49,   55,   50,   55,   50,
       83,   83,   56,   51,   56,   51,   65,   87,   65,  139,
       66,   89,   66,   83,   83,   90,   92,   92,  140,   88,
       88,   88,   88,   88,   84,   98,   52,   99,   52,   57,
       58,  272,   59,   60,   61,  101,   67,   62,   67,   68,

      108,   68,  102,  108,  108,  271,   63,   91,   91,   91,
       91,   91,  109,  110,  114,  133,  133,  111,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   69,  121,  133,
      133,  115,  268,  134,  136,  136,  136,  136,  136,  243,
      122,  122,  122,  122,  122,  135,  135,  135,  135,  135,
      264,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   71,   70,   70,
       72,   73,   74,   72,   75,   72,   76,   72,   75,   75,
       72,   75,   75,   77,   77,   77,   77,   77,   78,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   79,   79,   79,   80,   79,   79,   79,   79,   81,
       79,   79,   79,   79,   79,   79,   79,   79,   82,   79,
       72,   72,  112,  108,  128,  143,  129,   83,   83,   91,
       91,   91,   91,   91,  101,  156,  109,  110,  133,  133,
      157,  111,  198,  108,  108,  113,  113,  113,   86,  101,
      108,  130,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  127,  127,  127,  127,  127,   85,   87,  128,  145,
      129,  166,  165,  266,  258,  147,  147,  170,  243,   88,

       88,   88,   88,   88,  148,  148,  171,   88,   88,   88,
       88,   88,  146,  261,  120,  132,  107,  160,  108,  107,
      107,  107,  107,  107,  107,  107,  161,  107,  107,  162,
      162,  162,  162,  162,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  163,  107,  107,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  107,  107,  119,  121,
      128,  168,  129,  143,  214,  256,  128,  170,  129,  178,
      215,  122,  122,  122,  122,  122,  171,  143,  179,  122,
      122,  122,  122,  122,  169,  252,   86,  130,  174,  174,

      174,  174,  174,  130,  134,   85,  175,  175,  145,  101,
       86,  128,  178,  129,  160,  108,  135,  135,  135,  135,
      135,  179,  248,  161,  135,  135,  135,  135,  135,  198,
      108,  146,  177,  174,  174,  174,  174,  174,  130,  182,
      163,  175,  273,  136,  136,  136,  136,  136,  193,  108,
      196,  108,  183,  184,  228,  185,  166,  119,  166,  246,
      168,  238,  197,  197,  197,  197,  197,  177,  127,  127,
      127,  127,  127,  108,  199,  128,  216,  129,  240,  120,
      194,  120,  217,  169,  193,  108,  195,  200,  201,  108,
      201,  174,  174,  174,  174,  174,  207,  207,  207,  207,

      207,  210,  132,  108,  229,  182,  232,  241,  108,  224,
      230,  108,  233,  199,  211,  212,  194,  212,  183,  184,
      263,  185,  195,  196,  108,  204,  200,  201,  234,  201,
      209,  255,  244,  108,  235,  197,  197,  197,  197,  197,
      242,  161,  108,  108,  225,  108,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  197,  197,  197,  197,
      197,  210,  214,  216,  237,  108,  238,  229,  215,  217,
      226,  245,  226,  230,  211,  212,  232,  212,  234,  238,
      206,  108,  233,  240,  235,  209,  249,  108,  227,  247,
      227,  108,  250,  244,  108,  108,  240,  249,  108,  253,

      108,  262,  161,  250,  253,  108,  237,  257,  258,  251,
      257,  258,  266,  258,  260,  266,  258,  254,  259,  269,
      270,  259,  254,  269,  270,  236,  212,  206,  206,  206,
      204,  231,  201,  223,  267,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   85,   85,
       85,  222,   85,   85,   85,   85,   85,   85,   85,   94,
      221,  188,  219,  218,   94,   94,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  117,  117,  117,

      117,  117,  117,  117,  117,  117,  117,  117,  119,  119,
      119,  213,  119,  119,  119,  119,  119,  119,  119,  123,
      206,  273,  203,  202,  123,  123,  127,  108,  127,  192,
      127,  191,  127,  131,  190,  131,  189,  131,  101,  131,
      138,  188,  101,  101,  187,  138,  138,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  149,  149,
      186,  149,  149,  149,  149,  149,  149,  149,  149,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  176,  181,  180,  176,  176,  173,  176,  205,  172,

      118,  108,  108,  159,  205,  208,  158,  155,  154,  101,
      153,  208,  220,  101,  152,  151,  150,  142,  141,  137,
      126,  220,  239,  125,  124,  239,  239,  120,  118,  116,
      239,  239,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  108,  106,  105,  104,  103,  100,   97,
       96,   95,   93,   92,   84,   84,   84,   84,   86,   84,
      273,   17,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273
    } ;

static const flex_int16_t yy_chk[915] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    7,    3,    8,    4,
       19,   19,    7,    3,    8,    4,   11,   23,   12,   80,
       11,   28,   12,   20,   20,   28,   31,   31,   80,   23,
       23,   23,   23,   23,   28,   40,    3,   40,    4,    9,
        9,  271,    9,    9,    9,   42,   11,    9,   12,   11,

       52,   12,   42,  225,   51,  268,    9,   29,   29,   29,
       29,   29,   48,   48,   51,   73,   73,   48,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   13,   60,   74,
       74,   52,  264,   76,   77,   77,   77,   77,   77,  225,
       60,   60,   60,   60,   60,   76,   76,   76,   76,   76,
      261,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   50,   50,   70,   85,   70,   83,   83,   91,
       91,   91,   91,   91,  102,  104,  109,  109,  133,  133,
      104,  109,  165,  165,  242,   50,   50,   50,   85,  102,
      115,   70,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   71,   71,   71,   71,   71,   86,   87,   71,   86,
       71,  119,  115,  262,  262,   88,  147,  170,  242,   87,

       87,   87,   87,   87,   88,  147,  170,   88,   88,   88,
       88,   88,   86,  256,  119,   71,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  120,  121,
      127,  120,  127,  144,  184,  252,  130,  122,  130,  178,
      184,  121,  121,  121,  121,  121,  122,  145,  178,  122,
      122,  122,  122,  122,  120,  247,  144,  127,  128,  128,

      128,  128,  128,  130,  134,  146,  128,  128,  146,  241,
      145,  131,  135,  131,  160,  160,  134,  134,  134,  134,
      134,  135,  240,  160,  135,  135,  135,  135,  135,  198,
      198,  146,  128,  129,  129,  129,  129,  129,  131,  148,
      160,  129,  129,  136,  136,  136,  136,  136,  161,  161,
      163,  163,  148,  148,  198,  148,  167,  169,  168,  236,
      169,  220,  163,  163,  163,  163,  163,  129,  132,  132,
      132,  132,  132,  194,  171,  132,  185,  132,  220,  167,
      161,  168,  185,  169,  193,  193,  161,  171,  171,  260,
      171,  174,  174,  174,  174,  174,  177,  177,  177,  177,

      177,  179,  132,  195,  201,  182,  212,  222,  251,  194,
      201,  224,  212,  199,  179,  179,  193,  179,  182,  182,
      260,  182,  193,  196,  196,  174,  199,  199,  213,  199,
      177,  251,  226,  226,  213,  196,  196,  196,  196,  196,
      224,  226,  228,  227,  195,  197,  207,  207,  207,  207,
      207,  209,  209,  209,  209,  209,  197,  197,  197,  197,
      197,  210,  214,  216,  237,  245,  238,  229,  214,  216,
      227,  228,  197,  229,  210,  210,  232,  210,  234,  239,
      207,  255,  232,  238,  234,  209,  243,  243,  227,  237,
      197,  259,  243,  244,  244,  263,  239,  249,  249,  250,

      250,  259,  244,  249,  253,  253,  219,  254,  254,  245,
      257,  257,  265,  265,  255,  266,  266,  250,  254,  267,
      267,  257,  253,  269,  269,  218,  211,  208,  206,  205,
      204,  202,  200,  192,  263,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  277,  277,
      277,  190,  277,  277,  277,  277,  277,  277,  277,  278,
      189,  188,  187,  186,  278,  278,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  281,  281,
      281,  183,  281,  281,  281,  281,  281,  281,  281,  282,
      176,  175,  173,  172,  282,  282,  283,  164,  283,  159,
      283,  158,  283,  284,  157,  284,  156,  284,  155,  284,
      285,  154,  153,  152,  151,  285,  285,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  287,  287,
      150,  287,  287,  287,  287,  287,  287,  287,  287,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  290,  141,  139,  290,  290,  125,  290,  291,  124,

      117,  114,  107,  106,  291,  292,  105,  103,  100,   99,
       98,  292,  293,   97,   96,   95,   93,   82,   81,   78,
       69,  293,  294,   68,   67,  294,  294,   59,   58,   56,
      294,  294,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,   47,   46,   45,   44,   43,   41,   39,
       38,   37,   35,   33,   30,   27,   26,   25,   22,   21,
       17,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "v9.l"
#line 2 "v9.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_COMMENT_SIZE 2048
static char comment_buffer[MAX_COMMENT_SIZE];
static int comment_index = 0;

static char print_string[1024];
static char print_args[1024];
static int print_state_string_captured = 0;
static int at_count = 0;
static int arg_count = 0;
static int parentheses_count = 0;

static char* symbolTable[256];
static int symbolCount = 0;

int while_parantheses_count = 0;
    char while_condition_buffer[1024];
    int while_condition_index = 0;

int isDeclared(const char* id) {
    int i;
    for(i = 0; i < symbolCount; i++){
        if(strcmp(symbolTable[i], id) == 0) return 1;
    }
    return 0;
}

void reset_print_buffers() {
    memset(print_string, 0, sizeof(print_string));
    memset(print_args, 0, sizeof(print_args));
    print_state_string_captured = 0;
    at_count = 0;
    arg_count = 0;
    parentheses_count = 0;
}

void reset_while_stats(){
        memset(while_condition_buffer, 0, sizeof(while_condition_buffer));
        while_parantheses_count = 0;

    }

void count_at_symbols(const char* s) {
    int i;
    for (i = 0; s[i]; i++) {
        if (s[i] == '@') at_count++;
    }
}

void finalize_print_statement() {
    if (!print_state_string_captured) {
        printf("INVALID PRINT STATEMENT: Missing string.\n");
        return;
    }
    if (at_count != arg_count) {
        printf("INVALID PRINT STATEMENT: @ count (%d) != argument count (%d).\n", at_count, arg_count);
        return;
    }
    printf("VALID PRINT STATEMENT: %s\n", print_string);
}

int validate_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (text[0] < 'a' || text[0] > 'z') return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9')) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_char_const(const char *text) {
    int len = strlen(text);
    if (text[0] == '\'' && text[len - 1] == '\'') {
        if (text[1] == '\\' && len == 4) return 1;
        else if (text[1] != '\\' && len == 3) return 1;
    }
    return 0;
}

int validate_decimal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '9') return 0;
    }
    return 1;
}

int validate_octal(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] < '0' || text[i] > '7') return 0;
    }
    return 1;
}

int validate_binary(const char *text) {
    int i;
    for (i = 0; text[i] != '\0'; i++) {
        if (text[i] != '0' && text[i] != '1') return 0;
    }
    return 1;
}

int validate_array_identifier(const char *text) {
    const char *keywords[] = {
        "int","char","if","else","while","for","main","begin","end",
        "print","scan","program","VarDecl","inc","dec", NULL
    };
    int i;
    for (i = 0; keywords[i] != NULL; i++) {
        if (strcmp(text, keywords[i]) == 0) return 0;
    }
    if (!((text[0] >= 'a' && text[0] <= 'z') || (text[0] >= 'A' && text[0] <= 'Z'))) return 0;
    {
        int underscore = 0;
        int j;
        for (j = 0; text[j] != '\0'; j++) {
            char c = text[j];
            if (c == '_') {
                underscore++;
                if (underscore > 1) return 0;
            } else if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))) {
                return 0;
            }
        }
    }
    return 1;
}

int validate_relational_expression(char * condition){
        char id1[256],op[3],id2[256];
        if(sscanf(condition,"%s %s %s",id1,op,id2)==3){
            if(!validate_identifier(id1) || !validate_identifier(id2)){
                return 0;
            }
            if(!(strcmp(op,"=")||strcmp(op,"<>")||strcmp(op,">")||strcmp(op,"<")||strcmp(op,">=")||strcmp(op,"<="))){
                return 0;
            }
            return 1;
        }
        else if(sscanf(condition,"%s",id1)==1){
            return validate_identifier(id1);
        }
        return 0;
    }

void check_while_condition(){
        while_condition_buffer[while_condition_index] = '\0';
        if(validate_relational_expression(while_condition_buffer)){
            printf("VALID CONDITION IN WHILE LOOP\n");
        }
        else{
            printf("INVALID CONDITION IN WHILE LOOP\n");
        }
}
#line 915 "lex.yy.c"

#line 917 "lex.yy.c"

#define INITIAL 0
#define VARDECL 1
#define NUMRELATIONS 2
#define COMMENT 3
#define PRINT 4
#define WHILE 5
#define CONDITION 6
#define FOR 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 186 "v9.l"


#line 1144 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 862 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 188 "v9.l"
{ BEGIN(VARDECL); printf("BEGIN VARIABLE DECLARATION\n"); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 190 "v9.l"
{
    BEGIN(INITIAL);
    printf("END VARIABLE DECLARATION\n");
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 195 "v9.l"
{
    char lineCopy[1024];
    strncpy(lineCopy, yytext, 1023);
    lineCopy[1023] = '\0';
    {
        char *commentStart = strstr(lineCopy, "//");
        if(commentStart) {
            printf("COMMENT: %s\n", commentStart);
            *commentStart = '\0';
        }
    }
    if (strchr(lineCopy, '[')) {
        char id[64], typ[16];
        int size;
        if (sscanf(lineCopy, " ( %63[^[]%*c%d%*c , %15[^)] ) ;", id, &size, typ) == 3) {
            char *nl = strpbrk(typ, " \t");
            if (nl) *nl = '\0';
            if (size > 0 && validate_array_identifier(id)) {
                printf("VALID ARRAY DECLARATION: (%s[%d], %s)\n", id, size, typ);
                symbolTable[symbolCount++] = strdup(id);
            }
            else
                printf("INVALID ARRAY DECLARATION: %s\n", yytext);
        } else {
            printf("INVALID ARRAY DECLARATION: %s\n", yytext);
        }
    } else {
        char id[64], typ[16];
        if (sscanf(lineCopy, " ( %63[^,] , %15[^)] ) ;", id, typ) == 2) {
            char *nl = strpbrk(typ, " \t");
            if(nl) *nl = '\0';
            if (validate_identifier(id)) {
                printf("VALID VARIABLE DECLARATION: (%s, %s)\n", id, typ);
                symbolTable[symbolCount++] = strdup(id);
            }
            else
                printf("INVALID VARIABLE DECLARATION: %s\n", yytext);
        } else {
            printf("INVALID VARIABLE DECLARATION: %s\n", yytext);
        }
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 238 "v9.l"
{
    printf("COMMENT: %s\n", yytext);
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 242 "v9.l"
{
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 245 "v9.l"
{
    printf("INVALID VARIABLE DECLARATION: %s", yytext);
}
	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "v9.l"
{
    printf("KEYWORD: for\n");
    BEGIN(FOR);
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 254 "v9.l"
{
    /* Skip whitespace and newlines */
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 258 "v9.l"
{
    printf("FOR-DO KEYWORD: to\n");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 262 "v9.l"
{
    printf("FOR-DO KEYWORD: inc\n");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 266 "v9.l"
{
    printf("FOR-DO KEYWORD: dec\n");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 270 "v9.l"
{
    printf("FOR-DO KEYWORD: do\n");
    BEGIN(INITIAL); 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 275 "v9.l"
{
    printf("FOR-DO INDEX VARIABLE: %s\n", yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 279 "v9.l"
{
    printf("ASSIGNMENT OPERATOR (FOR-DO): %s\n", yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 283 "v9.l"
{
    printf("FOR-DO CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 287 "v9.l"
{
    printf("FOR-DO INTEGER CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 291 "v9.l"
{
    printf("FOR-DO ARITHMETIC OPERATOR: %s\n", yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 295 "v9.l"
{
    printf("FOR-DO TOKEN: %s\n", yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 299 "v9.l"
{
    printf("KEYWORD: %s\n", yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 303 "v9.l"
{
    printf("KEYWORD: %s\n", yytext);
    reset_print_buffers();
    BEGIN(PRINT);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 309 "v9.l"
{
    printf("KEYWORD: %s\n", yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 313 "v9.l"
{
    printf("KEYWORD: %s\n",yytext);
    BEGIN(WHILE);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 318 "v9.l"
{
    if (validate_identifier(yytext)) {
        if (isDeclared(yytext)) printf("IDENTIFIER: %s\n", yytext);
        else printf("UNDEFINED IDENTIFIER: %s\n", yytext);
    }
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 325 "v9.l"
{
    printf("COMMENT: %s\n", yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 329 "v9.l"
{
    BEGIN(COMMENT);
    comment_index = 0;
    comment_buffer[0] = '\0';
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 335 "v9.l"
{
    printf("COMMENT (multiline): /*%s*/\n", comment_buffer);
    BEGIN(INITIAL);
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 340 "v9.l"
{
    if(comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = '\n';
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 347 "v9.l"
{
    if(comment_index < MAX_COMMENT_SIZE - 1) {
        comment_buffer[comment_index++] = yytext[0];
        comment_buffer[comment_index] = '\0';
    }
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 354 "v9.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_binary(tmp)) printf("BINARY INTEGER CONSTANT: (%s, 2)\n", tmp);
    else printf("INVALID BINARY CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 367 "v9.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_octal(tmp))
        printf("OCTAL INTEGER CONSTANT: (%s, 8)\n", tmp);
    else
        printf("INVALID OCTAL CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 382 "v9.l"
{
    char tmp[128];
    char *start = yytext + 1;
    while (*start == ' ' || *start == '\t') start++;
    {
        int value_len = (int)(strchr(yytext, ',') - start);
        strncpy(tmp, start, value_len);
        tmp[value_len] = '\0';
    }
    if (validate_decimal(tmp)) printf("DECIMAL INTEGER CONSTANT: (%s, 10)\n", tmp);
    else printf("INVALID DECIMAL CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 395 "v9.l"
{
    printf("INVALID INTEGER CONSTANT: Missing base in %s\n", yytext);
}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 399 "v9.l"
{
    if (validate_char_const(yytext)) printf("CHARACTER CONSTANT: %s\n", yytext);
    else printf("INVALID CHARACTER CONSTANT: %s\n", yytext);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 404 "v9.l"
{ parentheses_count++; }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 406 "v9.l"
{
    if(!print_state_string_captured) {
        strncpy(print_string, yytext, sizeof(print_string)-1);
        count_at_symbols(yytext);
        print_state_string_captured = 1;
    }
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 414 "v9.l"
{
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 417 "v9.l"
{
    arg_count++;
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 421 "v9.l"
{
    arg_count++;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 425 "v9.l"
{
    arg_count++;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 429 "v9.l"
{
    if (parentheses_count > 0) parentheses_count--;
    else printf("INVALID PRINT STATEMENT: Unmatched closing parenthesis.\n");
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 434 "v9.l"
{
    if (parentheses_count != 0) printf("INVALID PRINT STATEMENT: Parentheses not closed.\n");
    else finalize_print_statement();
    BEGIN(INITIAL);
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 440 "v9.l"
{
    if (parentheses_count != 0) printf("INVALID PRINT STATEMENT: Missing closing parenthesis and semicolon.\n");
    else printf("INVALID PRINT STATEMENT: Missing semicolon.\n");
    reset_print_buffers();
    BEGIN(INITIAL);
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 446 "v9.l"
{
    BEGIN(INITIAL);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 450 "v9.l"
{
 reset_while_stats();
 while_parantheses_count++;
 BEGIN(CONDITION);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 455 "v9.l"
{
    printf("VALID CONDITION IDENTIFIED INSIDE WHILE LOOP: %s\n",yytext);
 }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 458 "v9.l"
{
    while_parantheses_count--;
    if(while_parantheses_count!=0){
        printf("INVALID WHILE LOOP STATEMENT: MISSING MATCHING PARANTHESES\n");
        while_parantheses_count = 0;
    }
    BEGIN(WHILE);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 468 "v9.l"
{
    printf("KEYWORD: %s\n", yytext);
    while_parantheses_count++;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 473 "v9.l"
{
    while_parantheses_count--;
    if(while_parantheses_count){
        printf("ERROR: you have entered end without a matching begin\n");
    }
    else{
        printf("CORRECT WHILE LOOP\n");
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 484 "v9.l"
{
    printf("SEPARATOR: %s\n", yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 488 "v9.l"
{
    printf("ARITHMETIC OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 492 "v9.l"
{
    printf("RELATIONAL OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 496 "v9.l"
{
    printf("ASSIGNMENT OPERATOR (INTEGER): %s\n", yytext);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 500 "v9.l"
{
    printf("SEPARATOR: %s\n", yytext);
}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 504 "v9.l"
{
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 507 "v9.l"
{
    if (YYSTATE == PRINT) printf("INVALID PRINT STATEMENT: Unexpected token '%s'\n", yytext);
    else printf("UNKNOWN TOKEN: %s\n", yytext);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 512 "v9.l"
ECHO;
	YY_BREAK
#line 1713 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(VARDECL):
case YY_STATE_EOF(NUMRELATIONS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(PRINT):
case YY_STATE_EOF(WHILE):
case YY_STATE_EOF(CONDITION):
case YY_STATE_EOF(FOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 273);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 512 "v9.l"


int main(int argc, char **argv) {
    yylex();
    return 0;
}
